//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AffectedResource) DeepCopyInto(out *AffectedResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AffectedResource.
func (in *AffectedResource) DeepCopy() *AffectedResource {
	if in == nil {
		return nil
	}
	out := new(AffectedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BenchmarkBaseline) DeepCopyInto(out *BenchmarkBaseline) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BenchmarkBaseline.
func (in *BenchmarkBaseline) DeepCopy() *BenchmarkBaseline {
	if in == nil {
		return nil
	}
	out := new(BenchmarkBaseline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BenchmarkComparison) DeepCopyInto(out *BenchmarkComparison) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BenchmarkComparison.
func (in *BenchmarkComparison) DeepCopy() *BenchmarkComparison {
	if in == nil {
		return nil
	}
	out := new(BenchmarkComparison)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BenchmarkHardwareInfo) DeepCopyInto(out *BenchmarkHardwareInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BenchmarkHardwareInfo.
func (in *BenchmarkHardwareInfo) DeepCopy() *BenchmarkHardwareInfo {
	if in == nil {
		return nil
	}
	out := new(BenchmarkHardwareInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BenchmarkResultValue) DeepCopyInto(out *BenchmarkResultValue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BenchmarkResultValue.
func (in *BenchmarkResultValue) DeepCopy() *BenchmarkResultValue {
	if in == nil {
		return nil
	}
	out := new(BenchmarkResultValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BenchmarkSchedule) DeepCopyInto(out *BenchmarkSchedule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BenchmarkSchedule.
func (in *BenchmarkSchedule) DeepCopy() *BenchmarkSchedule {
	if in == nil {
		return nil
	}
	out := new(BenchmarkSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BenchmarkTarget) DeepCopyInto(out *BenchmarkTarget) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BenchmarkTarget.
func (in *BenchmarkTarget) DeepCopy() *BenchmarkTarget {
	if in == nil {
		return nil
	}
	out := new(BenchmarkTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomBenchmarkConfig) DeepCopyInto(out *CustomBenchmarkConfig) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]CustomMetricDef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomBenchmarkConfig.
func (in *CustomBenchmarkConfig) DeepCopy() *CustomBenchmarkConfig {
	if in == nil {
		return nil
	}
	out := new(CustomBenchmarkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomMetricDef) DeepCopyInto(out *CustomMetricDef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomMetricDef.
func (in *CustomMetricDef) DeepCopy() *CustomMetricDef {
	if in == nil {
		return nil
	}
	out := new(CustomMetricDef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriversConfig) DeepCopyInto(out *DriversConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriversConfig.
func (in *DriversConfig) DeepCopy() *DriversConfig {
	if in == nil {
		return nil
	}
	out := new(DriversConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaBenchmark) DeepCopyInto(out *GryviaBenchmark) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaBenchmark.
func (in *GryviaBenchmark) DeepCopy() *GryviaBenchmark {
	if in == nil {
		return nil
	}
	out := new(GryviaBenchmark)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaBenchmark) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaBenchmarkList) DeepCopyInto(out *GryviaBenchmarkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaBenchmark, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaBenchmarkList.
func (in *GryviaBenchmarkList) DeepCopy() *GryviaBenchmarkList {
	if in == nil {
		return nil
	}
	out := new(GryviaBenchmarkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaBenchmarkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaBenchmarkSpec) DeepCopyInto(out *GryviaBenchmarkSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	if in.MLPerf != nil {
		in, out := &in.MLPerf, &out.MLPerf
		*out = new(MLPerfConfig)
		**out = **in
	}
	if in.NCCL != nil {
		in, out := &in.NCCL, &out.NCCL
		*out = new(NCCLConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.GPUMemory != nil {
		in, out := &in.GPUMemory, &out.GPUMemory
		*out = new(GPUMemoryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.IOThroughput != nil {
		in, out := &in.IOThroughput, &out.IOThroughput
		*out = new(IOThroughputConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = new(CustomBenchmarkConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Baseline != nil {
		in, out := &in.Baseline, &out.Baseline
		*out = new(BenchmarkBaseline)
		(*in).DeepCopyInto(*out)
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(BenchmarkSchedule)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaBenchmarkSpec.
func (in *GryviaBenchmarkSpec) DeepCopy() *GryviaBenchmarkSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaBenchmarkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaBenchmarkStatus) DeepCopyInto(out *GryviaBenchmarkStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make(map[string]BenchmarkResultValue, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Comparison != nil {
		in, out := &in.Comparison, &out.Comparison
		*out = new(BenchmarkComparison)
		**out = **in
	}
	if in.Hardware != nil {
		in, out := &in.Hardware, &out.Hardware
		*out = new(BenchmarkHardwareInfo)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaBenchmarkStatus.
func (in *GryviaBenchmarkStatus) DeepCopy() *GryviaBenchmarkStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaBenchmarkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaGPUSharingPolicy) DeepCopyInto(out *GryviaGPUSharingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaGPUSharingPolicy.
func (in *GryviaGPUSharingPolicy) DeepCopy() *GryviaGPUSharingPolicy {
	if in == nil {
		return nil
	}
	out := new(GryviaGPUSharingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaGPUSharingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaGPUSharingPolicyList) DeepCopyInto(out *GryviaGPUSharingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaGPUSharingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaGPUSharingPolicyList.
func (in *GryviaGPUSharingPolicyList) DeepCopy() *GryviaGPUSharingPolicyList {
	if in == nil {
		return nil
	}
	out := new(GryviaGPUSharingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaGPUSharingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaGPUSharingPolicySpec) DeepCopyInto(out *GryviaGPUSharingPolicySpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TimeSlicing != nil {
		in, out := &in.TimeSlicing, &out.TimeSlicing
		*out = new(GPUTimeSlicingConfig)
		**out = **in
	}
	if in.FractionalGPU != nil {
		in, out := &in.FractionalGPU, &out.FractionalGPU
		*out = new(GPUFractionalConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MIG != nil {
		in, out := &in.MIG, &out.MIG
		*out = new(GPUMIGConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.QoS != nil {
		in, out := &in.QoS, &out.QoS
		*out = new(GPUSharingQoS)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(GPUSharingPriority)
		**out = **in
	}
	if in.TenantQuotas != nil {
		in, out := &in.TenantQuotas, &out.TenantQuotas
		*out = make([]GPUTenantQuota, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaGPUSharingPolicySpec.
func (in *GryviaGPUSharingPolicySpec) DeepCopy() *GryviaGPUSharingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(GryviaGPUSharingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaGPUSharingPolicyStatus) DeepCopyInto(out *GryviaGPUSharingPolicyStatus) {
	*out = *in
	if in.AffectedNodes != nil {
		in, out := &in.AffectedNodes, &out.AffectedNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CurrentAllocations != nil {
		in, out := &in.CurrentAllocations, &out.CurrentAllocations
		*out = new(GPUSharingAllocations)
		**out = **in
	}
	if in.PerPodUtilization != nil {
		in, out := &in.PerPodUtilization, &out.PerPodUtilization
		*out = make([]GPUPodUtilization, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaGPUSharingPolicyStatus.
func (in *GryviaGPUSharingPolicyStatus) DeepCopy() *GryviaGPUSharingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaGPUSharingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaGpuMemoryOptimizer) DeepCopyInto(out *GryviaGpuMemoryOptimizer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaGpuMemoryOptimizer.
func (in *GryviaGpuMemoryOptimizer) DeepCopy() *GryviaGpuMemoryOptimizer {
	if in == nil {
		return nil
	}
	out := new(GryviaGpuMemoryOptimizer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaGpuMemoryOptimizer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaGpuMemoryOptimizerList) DeepCopyInto(out *GryviaGpuMemoryOptimizerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaGpuMemoryOptimizer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaGpuMemoryOptimizerList.
func (in *GryviaGpuMemoryOptimizerList) DeepCopy() *GryviaGpuMemoryOptimizerList {
	if in == nil {
		return nil
	}
	out := new(GryviaGpuMemoryOptimizerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaGpuMemoryOptimizerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaGpuMemoryOptimizerSpec) DeepCopyInto(out *GryviaGpuMemoryOptimizerSpec) {
	*out = *in
	in.Scope.DeepCopyInto(&out.Scope)
	if in.OomPrevention != nil {
		in, out := &in.OomPrevention, &out.OomPrevention
		*out = new(OomPreventionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RightSizing != nil {
		in, out := &in.RightSizing, &out.RightSizing
		*out = new(RightSizingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.InferencePacking != nil {
		in, out := &in.InferencePacking, &out.InferencePacking
		*out = new(InferencePackingConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaGpuMemoryOptimizerSpec.
func (in *GryviaGpuMemoryOptimizerSpec) DeepCopy() *GryviaGpuMemoryOptimizerSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaGpuMemoryOptimizerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaGpuMemoryOptimizerStatus) DeepCopyInto(out *GryviaGpuMemoryOptimizerStatus) {
	*out = *in
	if in.MemoryEfficiency != nil {
		in, out := &in.MemoryEfficiency, &out.MemoryEfficiency
		*out = new(MemoryEfficiencyStatus)
		**out = **in
	}
	if in.LastAnalysisTime != nil {
		in, out := &in.LastAnalysisTime, &out.LastAnalysisTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaGpuMemoryOptimizerStatus.
func (in *GryviaGpuMemoryOptimizerStatus) DeepCopy() *GryviaGpuMemoryOptimizerStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaGpuMemoryOptimizerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaGpuNode) DeepCopyInto(out *GryviaGpuNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaGpuNode.
func (in *GryviaGpuNode) DeepCopy() *GryviaGpuNode {
	if in == nil {
		return nil
	}
	out := new(GryviaGpuNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaGpuNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaGpuNodeList) DeepCopyInto(out *GryviaGpuNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaGpuNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaGpuNodeList.
func (in *GryviaGpuNodeList) DeepCopy() *GryviaGpuNodeList {
	if in == nil {
		return nil
	}
	out := new(GryviaGpuNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaGpuNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaGpuNodeSpec) DeepCopyInto(out *GryviaGpuNodeSpec) {
	*out = *in
	if in.Drivers != nil {
		in, out := &in.Drivers, &out.Drivers
		*out = new(DriversConfig)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(HealthCheckConfig)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaGpuNodeSpec.
func (in *GryviaGpuNodeSpec) DeepCopy() *GryviaGpuNodeSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaGpuNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaGpuNodeStatus) DeepCopyInto(out *GryviaGpuNodeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GpuStatus != nil {
		in, out := &in.GpuStatus, &out.GpuStatus
		*out = make([]GpuStatus, len(*in))
		copy(*out, *in)
	}
	if in.LastHealthCheck != nil {
		in, out := &in.LastHealthCheck, &out.LastHealthCheck
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaGpuNodeStatus.
func (in *GryviaGpuNodeStatus) DeepCopy() *GryviaGpuNodeStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaGpuNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaHealthCheck) DeepCopyInto(out *GryviaHealthCheck) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaHealthCheck.
func (in *GryviaHealthCheck) DeepCopy() *GryviaHealthCheck {
	if in == nil {
		return nil
	}
	out := new(GryviaHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaHealthCheck) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaHealthCheckList) DeepCopyInto(out *GryviaHealthCheckList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaHealthCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaHealthCheckList.
func (in *GryviaHealthCheckList) DeepCopy() *GryviaHealthCheckList {
	if in == nil {
		return nil
	}
	out := new(GryviaHealthCheckList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaHealthCheckList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaHealthCheckSpec) DeepCopyInto(out *GryviaHealthCheckSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]HealthCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OnFailure != nil {
		in, out := &in.OnFailure, &out.OnFailure
		*out = new(FailureActions)
		**out = **in
	}
	if in.Remediation != nil {
		in, out := &in.Remediation, &out.Remediation
		*out = new(RemediationConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaHealthCheckSpec.
func (in *GryviaHealthCheckSpec) DeepCopy() *GryviaHealthCheckSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaHealthCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaHealthCheckStatus) DeepCopyInto(out *GryviaHealthCheckStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastCheckTime != nil {
		in, out := &in.LastCheckTime, &out.LastCheckTime
		*out = (*in).DeepCopy()
	}
	if in.NextCheckTime != nil {
		in, out := &in.NextCheckTime, &out.NextCheckTime
		*out = (*in).DeepCopy()
	}
	if in.CheckResults != nil {
		in, out := &in.CheckResults, &out.CheckResults
		*out = make([]HealthCheckResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AffectedResources != nil {
		in, out := &in.AffectedResources, &out.AffectedResources
		*out = make([]AffectedResource, len(*in))
		copy(*out, *in)
	}
	if in.RemediationHistory != nil {
		in, out := &in.RemediationHistory, &out.RemediationHistory
		*out = make([]RemediationEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaHealthCheckStatus.
func (in *GryviaHealthCheckStatus) DeepCopy() *GryviaHealthCheckStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaHealthCheckStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaMetric) DeepCopyInto(out *GryviaMetric) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaMetric.
func (in *GryviaMetric) DeepCopy() *GryviaMetric {
	if in == nil {
		return nil
	}
	out := new(GryviaMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaMetric) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaMetricList) DeepCopyInto(out *GryviaMetricList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaMetric, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaMetricList.
func (in *GryviaMetricList) DeepCopy() *GryviaMetricList {
	if in == nil {
		return nil
	}
	out := new(GryviaMetricList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaMetricList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaMetricSpec) DeepCopyInto(out *GryviaMetricSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = new(MetricThresholds)
		(*in).DeepCopyInto(*out)
	}
	if in.Visualization != nil {
		in, out := &in.Visualization, &out.Visualization
		*out = new(MetricVisualization)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaMetricSpec.
func (in *GryviaMetricSpec) DeepCopy() *GryviaMetricSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaMetricSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaMetricStatus) DeepCopyInto(out *GryviaMetricStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = (*in).DeepCopy()
	}
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]MetricHistoryEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaMetricStatus.
func (in *GryviaMetricStatus) DeepCopy() *GryviaMetricStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaMetricStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailureActions) DeepCopyInto(out *FailureActions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailureActions.
func (in *FailureActions) DeepCopy() *FailureActions {
	if in == nil {
		return nil
	}
	out := new(FailureActions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUFractionalConfig) DeepCopyInto(out *GPUFractionalConfig) {
	*out = *in
	if in.Oversubscription != nil {
		in, out := &in.Oversubscription, &out.Oversubscription
		*out = new(GPUOversubscription)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUFractionalConfig.
func (in *GPUFractionalConfig) DeepCopy() *GPUFractionalConfig {
	if in == nil {
		return nil
	}
	out := new(GPUFractionalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUMIGConfig) DeepCopyInto(out *GPUMIGConfig) {
	*out = *in
	if in.Profiles != nil {
		in, out := &in.Profiles, &out.Profiles
		*out = make([]GPUMIGProfile, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUMIGConfig.
func (in *GPUMIGConfig) DeepCopy() *GPUMIGConfig {
	if in == nil {
		return nil
	}
	out := new(GPUMIGConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUMIGProfile) DeepCopyInto(out *GPUMIGProfile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUMIGProfile.
func (in *GPUMIGProfile) DeepCopy() *GPUMIGProfile {
	if in == nil {
		return nil
	}
	out := new(GPUMIGProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUMemoryConfig) DeepCopyInto(out *GPUMemoryConfig) {
	*out = *in
	if in.Sizes != nil {
		in, out := &in.Sizes, &out.Sizes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Directions != nil {
		in, out := &in.Directions, &out.Directions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUMemoryConfig.
func (in *GPUMemoryConfig) DeepCopy() *GPUMemoryConfig {
	if in == nil {
		return nil
	}
	out := new(GPUMemoryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUOversubscription) DeepCopyInto(out *GPUOversubscription) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUOversubscription.
func (in *GPUOversubscription) DeepCopy() *GPUOversubscription {
	if in == nil {
		return nil
	}
	out := new(GPUOversubscription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPodUtilization) DeepCopyInto(out *GPUPodUtilization) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPodUtilization.
func (in *GPUPodUtilization) DeepCopy() *GPUPodUtilization {
	if in == nil {
		return nil
	}
	out := new(GPUPodUtilization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUSharingAllocations) DeepCopyInto(out *GPUSharingAllocations) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUSharingAllocations.
func (in *GPUSharingAllocations) DeepCopy() *GPUSharingAllocations {
	if in == nil {
		return nil
	}
	out := new(GPUSharingAllocations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUSharingPriority) DeepCopyInto(out *GPUSharingPriority) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUSharingPriority.
func (in *GPUSharingPriority) DeepCopy() *GPUSharingPriority {
	if in == nil {
		return nil
	}
	out := new(GPUSharingPriority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUSharingQoS) DeepCopyInto(out *GPUSharingQoS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUSharingQoS.
func (in *GPUSharingQoS) DeepCopy() *GPUSharingQoS {
	if in == nil {
		return nil
	}
	out := new(GPUSharingQoS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUTenantQuota) DeepCopyInto(out *GPUTenantQuota) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUTenantQuota.
func (in *GPUTenantQuota) DeepCopy() *GPUTenantQuota {
	if in == nil {
		return nil
	}
	out := new(GPUTenantQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUTimeSlicingConfig) DeepCopyInto(out *GPUTimeSlicingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUTimeSlicingConfig.
func (in *GPUTimeSlicingConfig) DeepCopy() *GPUTimeSlicingConfig {
	if in == nil {
		return nil
	}
	out := new(GPUTimeSlicingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuStatus) DeepCopyInto(out *GpuStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuStatus.
func (in *GpuStatus) DeepCopy() *GpuStatus {
	if in == nil {
		return nil
	}
	out := new(GpuStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheck) DeepCopyInto(out *HealthCheck) {
	*out = *in
	if in.Threshold != nil {
		in, out := &in.Threshold, &out.Threshold
		*out = new(HealthCheckThreshold)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheck.
func (in *HealthCheck) DeepCopy() *HealthCheck {
	if in == nil {
		return nil
	}
	out := new(HealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckConfig) DeepCopyInto(out *HealthCheckConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckConfig.
func (in *HealthCheckConfig) DeepCopy() *HealthCheckConfig {
	if in == nil {
		return nil
	}
	out := new(HealthCheckConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckResult) DeepCopyInto(out *HealthCheckResult) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckResult.
func (in *HealthCheckResult) DeepCopy() *HealthCheckResult {
	if in == nil {
		return nil
	}
	out := new(HealthCheckResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckTarget) DeepCopyInto(out *HealthCheckTarget) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckTarget.
func (in *HealthCheckTarget) DeepCopy() *HealthCheckTarget {
	if in == nil {
		return nil
	}
	out := new(HealthCheckTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckThreshold) DeepCopyInto(out *HealthCheckThreshold) {
	*out = *in
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(float64)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(float64)
		**out = **in
	}
	if in.Warning != nil {
		in, out := &in.Warning, &out.Warning
		*out = new(float64)
		**out = **in
	}
	if in.Critical != nil {
		in, out := &in.Critical, &out.Critical
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckThreshold.
func (in *HealthCheckThreshold) DeepCopy() *HealthCheckThreshold {
	if in == nil {
		return nil
	}
	out := new(HealthCheckThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOThroughputConfig) DeepCopyInto(out *IOThroughputConfig) {
	*out = *in
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOThroughputConfig.
func (in *IOThroughputConfig) DeepCopy() *IOThroughputConfig {
	if in == nil {
		return nil
	}
	out := new(IOThroughputConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferencePackingConfig) DeepCopyInto(out *InferencePackingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferencePackingConfig.
func (in *InferencePackingConfig) DeepCopy() *InferencePackingConfig {
	if in == nil {
		return nil
	}
	out := new(InferencePackingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobOutputSource) DeepCopyInto(out *JobOutputSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobOutputSource.
func (in *JobOutputSource) DeepCopy() *JobOutputSource {
	if in == nil {
		return nil
	}
	out := new(JobOutputSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobSelector) DeepCopyInto(out *JobSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobSelector.
func (in *JobSelector) DeepCopy() *JobSelector {
	if in == nil {
		return nil
	}
	out := new(JobSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MLPerfConfig) DeepCopyInto(out *MLPerfConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MLPerfConfig.
func (in *MLPerfConfig) DeepCopy() *MLPerfConfig {
	if in == nil {
		return nil
	}
	out := new(MLPerfConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryEfficiencyStatus) DeepCopyInto(out *MemoryEfficiencyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryEfficiencyStatus.
func (in *MemoryEfficiencyStatus) DeepCopy() *MemoryEfficiencyStatus {
	if in == nil {
		return nil
	}
	out := new(MemoryEfficiencyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryGrowthProfilingConfig) DeepCopyInto(out *MemoryGrowthProfilingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryGrowthProfilingConfig.
func (in *MemoryGrowthProfilingConfig) DeepCopy() *MemoryGrowthProfilingConfig {
	if in == nil {
		return nil
	}
	out := new(MemoryGrowthProfilingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricHistoryEntry) DeepCopyInto(out *MetricHistoryEntry) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricHistoryEntry.
func (in *MetricHistoryEntry) DeepCopy() *MetricHistoryEntry {
	if in == nil {
		return nil
	}
	out := new(MetricHistoryEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSource) DeepCopyInto(out *MetricSource) {
	*out = *in
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(PrometheusSource)
		**out = **in
	}
	if in.JobOutput != nil {
		in, out := &in.JobOutput, &out.JobOutput
		*out = new(JobOutputSource)
		**out = **in
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(WebhookSource)
		**out = **in
	}
	if in.Script != nil {
		in, out := &in.Script, &out.Script
		*out = new(ScriptSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSource.
func (in *MetricSource) DeepCopy() *MetricSource {
	if in == nil {
		return nil
	}
	out := new(MetricSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricThresholds) DeepCopyInto(out *MetricThresholds) {
	*out = *in
	if in.Warning != nil {
		in, out := &in.Warning, &out.Warning
		*out = new(ThresholdRange)
		(*in).DeepCopyInto(*out)
	}
	if in.Critical != nil {
		in, out := &in.Critical, &out.Critical
		*out = new(ThresholdRange)
		(*in).DeepCopyInto(*out)
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricThresholds.
func (in *MetricThresholds) DeepCopy() *MetricThresholds {
	if in == nil {
		return nil
	}
	out := new(MetricThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricVisualization) DeepCopyInto(out *MetricVisualization) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricVisualization.
func (in *MetricVisualization) DeepCopy() *MetricVisualization {
	if in == nil {
		return nil
	}
	out := new(MetricVisualization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NCCLConfig) DeepCopyInto(out *NCCLConfig) {
	*out = *in
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MessageSizes != nil {
		in, out := &in.MessageSizes, &out.MessageSizes
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NCCLConfig.
func (in *NCCLConfig) DeepCopy() *NCCLConfig {
	if in == nil {
		return nil
	}
	out := new(NCCLConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OomPreventionConfig) DeepCopyInto(out *OomPreventionConfig) {
	*out = *in
	if in.MemoryGrowthProfiling != nil {
		in, out := &in.MemoryGrowthProfiling, &out.MemoryGrowthProfiling
		*out = new(MemoryGrowthProfilingConfig)
		**out = **in
	}
	if in.PreemptiveAction != nil {
		in, out := &in.PreemptiveAction, &out.PreemptiveAction
		*out = new(PreemptiveActionConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OomPreventionConfig.
func (in *OomPreventionConfig) DeepCopy() *OomPreventionConfig {
	if in == nil {
		return nil
	}
	out := new(OomPreventionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizerScope) DeepCopyInto(out *OptimizerScope) {
	*out = *in
	if in.JobSelector != nil {
		in, out := &in.JobSelector, &out.JobSelector
		*out = new(JobSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizerScope.
func (in *OptimizerScope) DeepCopy() *OptimizerScope {
	if in == nil {
		return nil
	}
	out := new(OptimizerScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreemptiveActionConfig) DeepCopyInto(out *PreemptiveActionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreemptiveActionConfig.
func (in *PreemptiveActionConfig) DeepCopy() *PreemptiveActionConfig {
	if in == nil {
		return nil
	}
	out := new(PreemptiveActionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusSource) DeepCopyInto(out *PrometheusSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusSource.
func (in *PrometheusSource) DeepCopy() *PrometheusSource {
	if in == nil {
		return nil
	}
	out := new(PrometheusSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecommendationsConfig) DeepCopyInto(out *RecommendationsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecommendationsConfig.
func (in *RecommendationsConfig) DeepCopy() *RecommendationsConfig {
	if in == nil {
		return nil
	}
	out := new(RecommendationsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationConfig) DeepCopyInto(out *RemediationConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationConfig.
func (in *RemediationConfig) DeepCopy() *RemediationConfig {
	if in == nil {
		return nil
	}
	out := new(RemediationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationEvent) DeepCopyInto(out *RemediationEvent) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationEvent.
func (in *RemediationEvent) DeepCopy() *RemediationEvent {
	if in == nil {
		return nil
	}
	out := new(RemediationEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightSizingConfig) DeepCopyInto(out *RightSizingConfig) {
	*out = *in
	if in.Recommendations != nil {
		in, out := &in.Recommendations, &out.Recommendations
		*out = new(RecommendationsConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightSizingConfig.
func (in *RightSizingConfig) DeepCopy() *RightSizingConfig {
	if in == nil {
		return nil
	}
	out := new(RightSizingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScriptSource) DeepCopyInto(out *ScriptSource) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScriptSource.
func (in *ScriptSource) DeepCopy() *ScriptSource {
	if in == nil {
		return nil
	}
	out := new(ScriptSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThresholdRange) DeepCopyInto(out *ThresholdRange) {
	*out = *in
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(float64)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThresholdRange.
func (in *ThresholdRange) DeepCopy() *ThresholdRange {
	if in == nil {
		return nil
	}
	out := new(ThresholdRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookSource) DeepCopyInto(out *WebhookSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookSource.
func (in *WebhookSource) DeepCopy() *WebhookSource {
	if in == nil {
		return nil
	}
	out := new(WebhookSource)
	in.DeepCopyInto(out)
	return out
}
