//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricGpuNode) DeepCopyInto(out *FabricGpuNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricGpuNode.
func (in *FabricGpuNode) DeepCopy() *FabricGpuNode {
	if in == nil {
		return nil
	}
	out := new(FabricGpuNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricGpuNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricGpuNodeList) DeepCopyInto(out *FabricGpuNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricGpuNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricGpuNodeList.
func (in *FabricGpuNodeList) DeepCopy() *FabricGpuNodeList {
	if in == nil {
		return nil
	}
	out := new(FabricGpuNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricGpuNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricGpuNodeSpec) DeepCopyInto(out *FabricGpuNodeSpec) {
	*out = *in
	if in.Drivers != nil {
		in, out := &in.Drivers, &out.Drivers
		*out = new(DriversConfig)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(HealthCheckConfig)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricGpuNodeSpec.
func (in *FabricGpuNodeSpec) DeepCopy() *FabricGpuNodeSpec {
	if in == nil {
		return nil
	}
	out := new(FabricGpuNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricGpuNodeStatus) DeepCopyInto(out *FabricGpuNodeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GpuStatus != nil {
		in, out := &in.GpuStatus, &out.GpuStatus
		*out = make([]GpuStatus, len(*in))
		copy(*out, *in)
	}
	if in.LastHealthCheck != nil {
		in, out := &in.LastHealthCheck, &out.LastHealthCheck
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricGpuNodeStatus.
func (in *FabricGpuNodeStatus) DeepCopy() *FabricGpuNodeStatus {
	if in == nil {
		return nil
	}
	out := new(FabricGpuNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriversConfig) DeepCopyInto(out *DriversConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriversConfig.
func (in *DriversConfig) DeepCopy() *DriversConfig {
	if in == nil {
		return nil
	}
	out := new(DriversConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckConfig) DeepCopyInto(out *HealthCheckConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckConfig.
func (in *HealthCheckConfig) DeepCopy() *HealthCheckConfig {
	if in == nil {
		return nil
	}
	out := new(HealthCheckConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuStatus) DeepCopyInto(out *GpuStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuStatus.
func (in *GpuStatus) DeepCopy() *GpuStatus {
	if in == nil {
		return nil
	}
	out := new(GpuStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricGpuMemoryOptimizer) DeepCopyInto(out *FabricGpuMemoryOptimizer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricGpuMemoryOptimizer.
func (in *FabricGpuMemoryOptimizer) DeepCopy() *FabricGpuMemoryOptimizer {
	if in == nil {
		return nil
	}
	out := new(FabricGpuMemoryOptimizer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricGpuMemoryOptimizer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricGpuMemoryOptimizerList) DeepCopyInto(out *FabricGpuMemoryOptimizerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricGpuMemoryOptimizer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricGpuMemoryOptimizerList.
func (in *FabricGpuMemoryOptimizerList) DeepCopy() *FabricGpuMemoryOptimizerList {
	if in == nil {
		return nil
	}
	out := new(FabricGpuMemoryOptimizerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricGpuMemoryOptimizerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricGpuMemoryOptimizerSpec) DeepCopyInto(out *FabricGpuMemoryOptimizerSpec) {
	*out = *in
	in.Scope.DeepCopyInto(&out.Scope)
	if in.OomPrevention != nil {
		in, out := &in.OomPrevention, &out.OomPrevention
		*out = new(OomPreventionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RightSizing != nil {
		in, out := &in.RightSizing, &out.RightSizing
		*out = new(RightSizingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.InferencePacking != nil {
		in, out := &in.InferencePacking, &out.InferencePacking
		*out = new(InferencePackingConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricGpuMemoryOptimizerSpec.
func (in *FabricGpuMemoryOptimizerSpec) DeepCopy() *FabricGpuMemoryOptimizerSpec {
	if in == nil {
		return nil
	}
	out := new(FabricGpuMemoryOptimizerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricGpuMemoryOptimizerStatus) DeepCopyInto(out *FabricGpuMemoryOptimizerStatus) {
	*out = *in
	if in.MemoryEfficiency != nil {
		in, out := &in.MemoryEfficiency, &out.MemoryEfficiency
		*out = new(MemoryEfficiencyStatus)
		**out = **in
	}
	if in.LastAnalysisTime != nil {
		in, out := &in.LastAnalysisTime, &out.LastAnalysisTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricGpuMemoryOptimizerStatus.
func (in *FabricGpuMemoryOptimizerStatus) DeepCopy() *FabricGpuMemoryOptimizerStatus {
	if in == nil {
		return nil
	}
	out := new(FabricGpuMemoryOptimizerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizerScope) DeepCopyInto(out *OptimizerScope) {
	*out = *in
	if in.JobSelector != nil {
		in, out := &in.JobSelector, &out.JobSelector
		*out = new(JobSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizerScope.
func (in *OptimizerScope) DeepCopy() *OptimizerScope {
	if in == nil {
		return nil
	}
	out := new(OptimizerScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobSelector) DeepCopyInto(out *JobSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobSelector.
func (in *JobSelector) DeepCopy() *JobSelector {
	if in == nil {
		return nil
	}
	out := new(JobSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OomPreventionConfig) DeepCopyInto(out *OomPreventionConfig) {
	*out = *in
	if in.MemoryGrowthProfiling != nil {
		in, out := &in.MemoryGrowthProfiling, &out.MemoryGrowthProfiling
		*out = new(MemoryGrowthProfilingConfig)
		**out = **in
	}
	if in.PreemptiveAction != nil {
		in, out := &in.PreemptiveAction, &out.PreemptiveAction
		*out = new(PreemptiveActionConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OomPreventionConfig.
func (in *OomPreventionConfig) DeepCopy() *OomPreventionConfig {
	if in == nil {
		return nil
	}
	out := new(OomPreventionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryGrowthProfilingConfig) DeepCopyInto(out *MemoryGrowthProfilingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryGrowthProfilingConfig.
func (in *MemoryGrowthProfilingConfig) DeepCopy() *MemoryGrowthProfilingConfig {
	if in == nil {
		return nil
	}
	out := new(MemoryGrowthProfilingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreemptiveActionConfig) DeepCopyInto(out *PreemptiveActionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreemptiveActionConfig.
func (in *PreemptiveActionConfig) DeepCopy() *PreemptiveActionConfig {
	if in == nil {
		return nil
	}
	out := new(PreemptiveActionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightSizingConfig) DeepCopyInto(out *RightSizingConfig) {
	*out = *in
	if in.Recommendations != nil {
		in, out := &in.Recommendations, &out.Recommendations
		*out = new(RecommendationsConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightSizingConfig.
func (in *RightSizingConfig) DeepCopy() *RightSizingConfig {
	if in == nil {
		return nil
	}
	out := new(RightSizingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecommendationsConfig) DeepCopyInto(out *RecommendationsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecommendationsConfig.
func (in *RecommendationsConfig) DeepCopy() *RecommendationsConfig {
	if in == nil {
		return nil
	}
	out := new(RecommendationsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferencePackingConfig) DeepCopyInto(out *InferencePackingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferencePackingConfig.
func (in *InferencePackingConfig) DeepCopy() *InferencePackingConfig {
	if in == nil {
		return nil
	}
	out := new(InferencePackingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryEfficiencyStatus) DeepCopyInto(out *MemoryEfficiencyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryEfficiencyStatus.
func (in *MemoryEfficiencyStatus) DeepCopy() *MemoryEfficiencyStatus {
	if in == nil {
		return nil
	}
	out := new(MemoryEfficiencyStatus)
	in.DeepCopyInto(out)
	return out
}
