//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAIJob) DeepCopyInto(out *FabricAIJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAIJob.
func (in *FabricAIJob) DeepCopy() *FabricAIJob {
	if in == nil {
		return nil
	}
	out := new(FabricAIJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricAIJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAIJobList) DeepCopyInto(out *FabricAIJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricAIJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAIJobList.
func (in *FabricAIJobList) DeepCopy() *FabricAIJobList {
	if in == nil {
		return nil
	}
	out := new(FabricAIJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricAIJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAIJobSpec) DeepCopyInto(out *FabricAIJobSpec) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Distributed != nil {
		in, out := &in.Distributed, &out.Distributed
		*out = new(DistributedConfig)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAIJobSpec.
func (in *FabricAIJobSpec) DeepCopy() *FabricAIJobSpec {
	if in == nil {
		return nil
	}
	out := new(FabricAIJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAIJobStatus) DeepCopyInto(out *FabricAIJobStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.NodesAllocated != nil {
		in, out := &in.NodesAllocated, &out.NodesAllocated
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(JobMetrics)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAIJobStatus.
func (in *FabricAIJobStatus) DeepCopy() *FabricAIJobStatus {
	if in == nil {
		return nil
	}
	out := new(FabricAIJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedConfig) DeepCopyInto(out *DistributedConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedConfig.
func (in *DistributedConfig) DeepCopy() *DistributedConfig {
	if in == nil {
		return nil
	}
	out := new(DistributedConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobMetrics) DeepCopyInto(out *JobMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobMetrics.
func (in *JobMetrics) DeepCopy() *JobMetrics {
	if in == nil {
		return nil
	}
	out := new(JobMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricLiveExperiment) DeepCopyInto(out *FabricLiveExperiment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricLiveExperiment.
func (in *FabricLiveExperiment) DeepCopy() *FabricLiveExperiment {
	if in == nil {
		return nil
	}
	out := new(FabricLiveExperiment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricLiveExperiment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricLiveExperimentList) DeepCopyInto(out *FabricLiveExperimentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricLiveExperiment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricLiveExperimentList.
func (in *FabricLiveExperimentList) DeepCopy() *FabricLiveExperimentList {
	if in == nil {
		return nil
	}
	out := new(FabricLiveExperimentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricLiveExperimentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricLiveExperimentSpec) DeepCopyInto(out *FabricLiveExperimentSpec) {
	*out = *in
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = make([]ExperimentJob, len(*in))
		copy(*out, *in)
	}
	in.Comparison.DeepCopyInto(&out.Comparison)
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(StrategyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = new(NotificationConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricLiveExperimentSpec.
func (in *FabricLiveExperimentSpec) DeepCopy() *FabricLiveExperimentSpec {
	if in == nil {
		return nil
	}
	out := new(FabricLiveExperimentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricLiveExperimentStatus) DeepCopyInto(out *FabricLiveExperimentStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.Leaderboard != nil {
		in, out := &in.Leaderboard, &out.Leaderboard
		*out = make([]LeaderboardEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricLiveExperimentStatus.
func (in *FabricLiveExperimentStatus) DeepCopy() *FabricLiveExperimentStatus {
	if in == nil {
		return nil
	}
	out := new(FabricLiveExperimentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExperimentJob) DeepCopyInto(out *ExperimentJob) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExperimentJob.
func (in *ExperimentJob) DeepCopy() *ExperimentJob {
	if in == nil {
		return nil
	}
	out := new(ExperimentJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComparisonConfig) DeepCopyInto(out *ComparisonConfig) {
	*out = *in
	if in.SecondaryMetrics != nil {
		in, out := &in.SecondaryMetrics, &out.SecondaryMetrics
		*out = make([]SecondaryMetric, len(*in))
		copy(*out, *in)
	}
	if in.MetricSource != nil {
		in, out := &in.MetricSource, &out.MetricSource
		*out = new(MetricSourceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComparisonConfig.
func (in *ComparisonConfig) DeepCopy() *ComparisonConfig {
	if in == nil {
		return nil
	}
	out := new(ComparisonConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecondaryMetric) DeepCopyInto(out *SecondaryMetric) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecondaryMetric.
func (in *SecondaryMetric) DeepCopy() *SecondaryMetric {
	if in == nil {
		return nil
	}
	out := new(SecondaryMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSourceConfig) DeepCopyInto(out *MetricSourceConfig) {
	*out = *in
	if in.Patterns != nil {
		in, out := &in.Patterns, &out.Patterns
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSourceConfig.
func (in *MetricSourceConfig) DeepCopy() *MetricSourceConfig {
	if in == nil {
		return nil
	}
	out := new(MetricSourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StrategyConfig) DeepCopyInto(out *StrategyConfig) {
	*out = *in
	if in.ComparisonPoints != nil {
		in, out := &in.ComparisonPoints, &out.ComparisonPoints
		*out = make([]ComparisonPoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EarlyTermination != nil {
		in, out := &in.EarlyTermination, &out.EarlyTermination
		*out = new(EarlyTerminationConfig)
		**out = **in
	}
	if in.AnomalyDetection != nil {
		in, out := &in.AnomalyDetection, &out.AnomalyDetection
		*out = new(AnomalyDetectionConfig)
		**out = **in
	}
	if in.Intervention != nil {
		in, out := &in.Intervention, &out.Intervention
		*out = new(InterventionConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StrategyConfig.
func (in *StrategyConfig) DeepCopy() *StrategyConfig {
	if in == nil {
		return nil
	}
	out := new(StrategyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComparisonPoint) DeepCopyInto(out *ComparisonPoint) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComparisonPoint.
func (in *ComparisonPoint) DeepCopy() *ComparisonPoint {
	if in == nil {
		return nil
	}
	out := new(ComparisonPoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EarlyTerminationConfig) DeepCopyInto(out *EarlyTerminationConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EarlyTerminationConfig.
func (in *EarlyTerminationConfig) DeepCopy() *EarlyTerminationConfig {
	if in == nil {
		return nil
	}
	out := new(EarlyTerminationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnomalyDetectionConfig) DeepCopyInto(out *AnomalyDetectionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnomalyDetectionConfig.
func (in *AnomalyDetectionConfig) DeepCopy() *AnomalyDetectionConfig {
	if in == nil {
		return nil
	}
	out := new(AnomalyDetectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterventionConfig) DeepCopyInto(out *InterventionConfig) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterventionConfig.
func (in *InterventionConfig) DeepCopy() *InterventionConfig {
	if in == nil {
		return nil
	}
	out := new(InterventionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationConfig) DeepCopyInto(out *NotificationConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationConfig.
func (in *NotificationConfig) DeepCopy() *NotificationConfig {
	if in == nil {
		return nil
	}
	out := new(NotificationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaderboardEntry) DeepCopyInto(out *LeaderboardEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaderboardEntry.
func (in *LeaderboardEntry) DeepCopy() *LeaderboardEntry {
	if in == nil {
		return nil
	}
	out := new(LeaderboardEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTrainingProfiler) DeepCopyInto(out *FabricTrainingProfiler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTrainingProfiler.
func (in *FabricTrainingProfiler) DeepCopy() *FabricTrainingProfiler {
	if in == nil {
		return nil
	}
	out := new(FabricTrainingProfiler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricTrainingProfiler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTrainingProfilerList) DeepCopyInto(out *FabricTrainingProfilerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricTrainingProfiler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTrainingProfilerList.
func (in *FabricTrainingProfilerList) DeepCopy() *FabricTrainingProfilerList {
	if in == nil {
		return nil
	}
	out := new(FabricTrainingProfilerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricTrainingProfilerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTrainingProfilerSpec) DeepCopyInto(out *FabricTrainingProfilerSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	in.Metrics.DeepCopyInto(&out.Metrics)
	in.Analysis.DeepCopyInto(&out.Analysis)
	out.Output = in.Output
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTrainingProfilerSpec.
func (in *FabricTrainingProfilerSpec) DeepCopy() *FabricTrainingProfilerSpec {
	if in == nil {
		return nil
	}
	out := new(FabricTrainingProfilerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTrainingProfilerStatus) DeepCopyInto(out *FabricTrainingProfilerStatus) {
	*out = *in
	if in.TopRecommendations != nil {
		in, out := &in.TopRecommendations, &out.TopRecommendations
		*out = make([]ProfilerRecommendation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastProfileTime != nil {
		in, out := &in.LastProfileTime, &out.LastProfileTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTrainingProfilerStatus.
func (in *FabricTrainingProfilerStatus) DeepCopy() *FabricTrainingProfilerStatus {
	if in == nil {
		return nil
	}
	out := new(FabricTrainingProfilerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfilerTarget) DeepCopyInto(out *ProfilerTarget) {
	*out = *in
	if in.JobSelector != nil {
		in, out := &in.JobSelector, &out.JobSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AutoProfile != nil {
		in, out := &in.AutoProfile, &out.AutoProfile
		*out = new(AutoProfileConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfilerTarget.
func (in *ProfilerTarget) DeepCopy() *ProfilerTarget {
	if in == nil {
		return nil
	}
	out := new(ProfilerTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoProfileConfig) DeepCopyInto(out *AutoProfileConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoProfileConfig.
func (in *AutoProfileConfig) DeepCopy() *AutoProfileConfig {
	if in == nil {
		return nil
	}
	out := new(AutoProfileConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfilerMetrics) DeepCopyInto(out *ProfilerMetrics) {
	*out = *in
	if in.GpuCompute != nil {
		in, out := &in.GpuCompute, &out.GpuCompute
		*out = new(GpuComputeMetrics)
		**out = **in
	}
	if in.GpuMemory != nil {
		in, out := &in.GpuMemory, &out.GpuMemory
		*out = new(GpuMemoryMetrics)
		**out = **in
	}
	if in.DataPipeline != nil {
		in, out := &in.DataPipeline, &out.DataPipeline
		*out = new(DataPipelineMetrics)
		**out = **in
	}
	if in.Communication != nil {
		in, out := &in.Communication, &out.Communication
		*out = new(CommunicationMetrics)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfilerMetrics.
func (in *ProfilerMetrics) DeepCopy() *ProfilerMetrics {
	if in == nil {
		return nil
	}
	out := new(ProfilerMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuComputeMetrics) DeepCopyInto(out *GpuComputeMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuComputeMetrics.
func (in *GpuComputeMetrics) DeepCopy() *GpuComputeMetrics {
	if in == nil {
		return nil
	}
	out := new(GpuComputeMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuMemoryMetrics) DeepCopyInto(out *GpuMemoryMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuMemoryMetrics.
func (in *GpuMemoryMetrics) DeepCopy() *GpuMemoryMetrics {
	if in == nil {
		return nil
	}
	out := new(GpuMemoryMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataPipelineMetrics) DeepCopyInto(out *DataPipelineMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataPipelineMetrics.
func (in *DataPipelineMetrics) DeepCopy() *DataPipelineMetrics {
	if in == nil {
		return nil
	}
	out := new(DataPipelineMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommunicationMetrics) DeepCopyInto(out *CommunicationMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommunicationMetrics.
func (in *CommunicationMetrics) DeepCopy() *CommunicationMetrics {
	if in == nil {
		return nil
	}
	out := new(CommunicationMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfilerAnalysis) DeepCopyInto(out *ProfilerAnalysis) {
	*out = *in
	if in.Recommendations != nil {
		in, out := &in.Recommendations, &out.Recommendations
		*out = new(RecommendationConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfilerAnalysis.
func (in *ProfilerAnalysis) DeepCopy() *ProfilerAnalysis {
	if in == nil {
		return nil
	}
	out := new(ProfilerAnalysis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecommendationConfig) DeepCopyInto(out *RecommendationConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecommendationConfig.
func (in *RecommendationConfig) DeepCopy() *RecommendationConfig {
	if in == nil {
		return nil
	}
	out := new(RecommendationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfilerOutput) DeepCopyInto(out *ProfilerOutput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfilerOutput.
func (in *ProfilerOutput) DeepCopy() *ProfilerOutput {
	if in == nil {
		return nil
	}
	out := new(ProfilerOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfilerRecommendation) DeepCopyInto(out *ProfilerRecommendation) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfilerRecommendation.
func (in *ProfilerRecommendation) DeepCopy() *ProfilerRecommendation {
	if in == nil {
		return nil
	}
	out := new(ProfilerRecommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricCheckpointGuard) DeepCopyInto(out *FabricCheckpointGuard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricCheckpointGuard.
func (in *FabricCheckpointGuard) DeepCopy() *FabricCheckpointGuard {
	if in == nil {
		return nil
	}
	out := new(FabricCheckpointGuard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricCheckpointGuard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricCheckpointGuardList) DeepCopyInto(out *FabricCheckpointGuardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricCheckpointGuard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricCheckpointGuardList.
func (in *FabricCheckpointGuardList) DeepCopy() *FabricCheckpointGuardList {
	if in == nil {
		return nil
	}
	out := new(FabricCheckpointGuardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricCheckpointGuardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricCheckpointGuardSpec) DeepCopyInto(out *FabricCheckpointGuardSpec) {
	*out = *in
	in.JobSelector.DeepCopyInto(&out.JobSelector)
	in.CheckpointPolicy.DeepCopyInto(&out.CheckpointPolicy)
	if in.Validation != nil {
		in, out := &in.Validation, &out.Validation
		*out = new(CheckpointValidation)
		**out = **in
	}
	if in.Restore != nil {
		in, out := &in.Restore, &out.Restore
		*out = new(RestorePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(CheckpointMonitoring)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricCheckpointGuardSpec.
func (in *FabricCheckpointGuardSpec) DeepCopy() *FabricCheckpointGuardSpec {
	if in == nil {
		return nil
	}
	out := new(FabricCheckpointGuardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricCheckpointGuardStatus) DeepCopyInto(out *FabricCheckpointGuardStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastCheckpointTime != nil {
		in, out := &in.LastCheckpointTime, &out.LastCheckpointTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricCheckpointGuardStatus.
func (in *FabricCheckpointGuardStatus) DeepCopy() *FabricCheckpointGuardStatus {
	if in == nil {
		return nil
	}
	out := new(FabricCheckpointGuardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobSelector) DeepCopyInto(out *JobSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobSelector.
func (in *JobSelector) DeepCopy() *JobSelector {
	if in == nil {
		return nil
	}
	out := new(JobSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointPolicy) DeepCopyInto(out *CheckpointPolicy) {
	*out = *in
	if in.EmergencyCheckpoint != nil {
		in, out := &in.EmergencyCheckpoint, &out.EmergencyCheckpoint
		*out = new(EmergencyCheckpointConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Replication != nil {
		in, out := &in.Replication, &out.Replication
		*out = new(ReplicationConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointPolicy.
func (in *CheckpointPolicy) DeepCopy() *CheckpointPolicy {
	if in == nil {
		return nil
	}
	out := new(CheckpointPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmergencyCheckpointConfig) DeepCopyInto(out *EmergencyCheckpointConfig) {
	*out = *in
	if in.Triggers != nil {
		in, out := &in.Triggers, &out.Triggers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmergencyCheckpointConfig.
func (in *EmergencyCheckpointConfig) DeepCopy() *EmergencyCheckpointConfig {
	if in == nil {
		return nil
	}
	out := new(EmergencyCheckpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationConfig) DeepCopyInto(out *ReplicationConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationConfig.
func (in *ReplicationConfig) DeepCopy() *ReplicationConfig {
	if in == nil {
		return nil
	}
	out := new(ReplicationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointValidation) DeepCopyInto(out *CheckpointValidation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointValidation.
func (in *CheckpointValidation) DeepCopy() *CheckpointValidation {
	if in == nil {
		return nil
	}
	out := new(CheckpointValidation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestorePolicy) DeepCopyInto(out *RestorePolicy) {
	*out = *in
	if in.InjectEnvVars != nil {
		in, out := &in.InjectEnvVars, &out.InjectEnvVars
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestorePolicy.
func (in *RestorePolicy) DeepCopy() *RestorePolicy {
	if in == nil {
		return nil
	}
	out := new(RestorePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointMonitoring) DeepCopyInto(out *CheckpointMonitoring) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointMonitoring.
func (in *CheckpointMonitoring) DeepCopy() *CheckpointMonitoring {
	if in == nil {
		return nil
	}
	out := new(CheckpointMonitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricGpuNode) DeepCopyInto(out *FabricGpuNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricGpuNode.
func (in *FabricGpuNode) DeepCopy() *FabricGpuNode {
	if in == nil {
		return nil
	}
	out := new(FabricGpuNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricGpuNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricGpuNodeList) DeepCopyInto(out *FabricGpuNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricGpuNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricGpuNodeList.
func (in *FabricGpuNodeList) DeepCopy() *FabricGpuNodeList {
	if in == nil {
		return nil
	}
	out := new(FabricGpuNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricGpuNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricGpuNodeSpec) DeepCopyInto(out *FabricGpuNodeSpec) {
	*out = *in
	if in.Drivers != nil {
		in, out := &in.Drivers, &out.Drivers
		*out = new(GpuDriversConfig)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(GpuHealthCheckConfig)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricGpuNodeSpec.
func (in *FabricGpuNodeSpec) DeepCopy() *FabricGpuNodeSpec {
	if in == nil {
		return nil
	}
	out := new(FabricGpuNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricGpuNodeStatus) DeepCopyInto(out *FabricGpuNodeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GpuStatus != nil {
		in, out := &in.GpuStatus, &out.GpuStatus
		*out = make([]GpuDeviceStatus, len(*in))
		copy(*out, *in)
	}
	if in.LastHealthCheck != nil {
		in, out := &in.LastHealthCheck, &out.LastHealthCheck
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricGpuNodeStatus.
func (in *FabricGpuNodeStatus) DeepCopy() *FabricGpuNodeStatus {
	if in == nil {
		return nil
	}
	out := new(FabricGpuNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuDriversConfig) DeepCopyInto(out *GpuDriversConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuDriversConfig.
func (in *GpuDriversConfig) DeepCopy() *GpuDriversConfig {
	if in == nil {
		return nil
	}
	out := new(GpuDriversConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuHealthCheckConfig) DeepCopyInto(out *GpuHealthCheckConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuHealthCheckConfig.
func (in *GpuHealthCheckConfig) DeepCopy() *GpuHealthCheckConfig {
	if in == nil {
		return nil
	}
	out := new(GpuHealthCheckConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuDeviceStatus) DeepCopyInto(out *GpuDeviceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuDeviceStatus.
func (in *GpuDeviceStatus) DeepCopy() *GpuDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(GpuDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricModelLineage) DeepCopyInto(out *FabricModelLineage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricModelLineage.
func (in *FabricModelLineage) DeepCopy() *FabricModelLineage {
	if in == nil {
		return nil
	}
	out := new(FabricModelLineage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricModelLineage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricModelLineageList) DeepCopyInto(out *FabricModelLineageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricModelLineage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricModelLineageList.
func (in *FabricModelLineageList) DeepCopy() *FabricModelLineageList {
	if in == nil {
		return nil
	}
	out := new(FabricModelLineageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricModelLineageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricModelLineageSpec) DeepCopyInto(out *FabricModelLineageSpec) {
	*out = *in
	out.Model = in.Model
	in.Provenance.DeepCopyInto(&out.Provenance)
	in.Compliance.DeepCopyInto(&out.Compliance)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricModelLineageSpec.
func (in *FabricModelLineageSpec) DeepCopy() *FabricModelLineageSpec {
	if in == nil {
		return nil
	}
	out := new(FabricModelLineageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricModelLineageStatus) DeepCopyInto(out *FabricModelLineageStatus) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricModelLineageStatus.
func (in *FabricModelLineageStatus) DeepCopy() *FabricModelLineageStatus {
	if in == nil {
		return nil
	}
	out := new(FabricModelLineageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelIdentity) DeepCopyInto(out *ModelIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelIdentity.
func (in *ModelIdentity) DeepCopy() *ModelIdentity {
	if in == nil {
		return nil
	}
	out := new(ModelIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvenanceSpec) DeepCopyInto(out *ProvenanceSpec) {
	*out = *in
	out.Code = in.Code
	in.Data.DeepCopyInto(&out.Data)
	in.Training.DeepCopyInto(&out.Training)
	in.Infrastructure.DeepCopyInto(&out.Infrastructure)
	in.Events.DeepCopyInto(&out.Events)
	in.Evaluation.DeepCopyInto(&out.Evaluation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvenanceSpec.
func (in *ProvenanceSpec) DeepCopy() *ProvenanceSpec {
	if in == nil {
		return nil
	}
	out := new(ProvenanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeProvenance) DeepCopyInto(out *CodeProvenance) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeProvenance.
func (in *CodeProvenance) DeepCopy() *CodeProvenance {
	if in == nil {
		return nil
	}
	out := new(CodeProvenance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataProvenance) DeepCopyInto(out *DataProvenance) {
	*out = *in
	if in.Datasets != nil {
		in, out := &in.Datasets, &out.Datasets
		*out = make([]DatasetReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataProvenance.
func (in *DataProvenance) DeepCopy() *DataProvenance {
	if in == nil {
		return nil
	}
	out := new(DataProvenance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasetReference) DeepCopyInto(out *DatasetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasetReference.
func (in *DatasetReference) DeepCopy() *DatasetReference {
	if in == nil {
		return nil
	}
	out := new(DatasetReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingProvenance) DeepCopyInto(out *TrainingProvenance) {
	*out = *in
	if in.Hyperparameters != nil {
		in, out := &in.Hyperparameters, &out.Hyperparameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingProvenance.
func (in *TrainingProvenance) DeepCopy() *TrainingProvenance {
	if in == nil {
		return nil
	}
	out := new(TrainingProvenance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureProvenance) DeepCopyInto(out *InfrastructureProvenance) {
	*out = *in
	if in.GPUNodes != nil {
		in, out := &in.GPUNodes, &out.GPUNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureProvenance.
func (in *InfrastructureProvenance) DeepCopy() *InfrastructureProvenance {
	if in == nil {
		return nil
	}
	out := new(InfrastructureProvenance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventsProvenance) DeepCopyInto(out *EventsProvenance) {
	*out = *in
	if in.Anomalies != nil {
		in, out := &in.Anomalies, &out.Anomalies
		*out = make([]AnomalyEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Interventions != nil {
		in, out := &in.Interventions, &out.Interventions
		*out = make([]InterventionEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CheckpointTimeline != nil {
		in, out := &in.CheckpointTimeline, &out.CheckpointTimeline
		*out = make([]CheckpointEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventsProvenance.
func (in *EventsProvenance) DeepCopy() *EventsProvenance {
	if in == nil {
		return nil
	}
	out := new(EventsProvenance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnomalyEvent) DeepCopyInto(out *AnomalyEvent) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnomalyEvent.
func (in *AnomalyEvent) DeepCopy() *AnomalyEvent {
	if in == nil {
		return nil
	}
	out := new(AnomalyEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterventionEvent) DeepCopyInto(out *InterventionEvent) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterventionEvent.
func (in *InterventionEvent) DeepCopy() *InterventionEvent {
	if in == nil {
		return nil
	}
	out := new(InterventionEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointEvent) DeepCopyInto(out *CheckpointEvent) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointEvent.
func (in *CheckpointEvent) DeepCopy() *CheckpointEvent {
	if in == nil {
		return nil
	}
	out := new(CheckpointEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvaluationProvenance) DeepCopyInto(out *EvaluationProvenance) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Benchmarks != nil {
		in, out := &in.Benchmarks, &out.Benchmarks
		*out = make([]BenchmarkResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvaluationProvenance.
func (in *EvaluationProvenance) DeepCopy() *EvaluationProvenance {
	if in == nil {
		return nil
	}
	out := new(EvaluationProvenance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BenchmarkResult) DeepCopyInto(out *BenchmarkResult) {
	*out = *in
	in.Date.DeepCopyInto(&out.Date)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BenchmarkResult.
func (in *BenchmarkResult) DeepCopy() *BenchmarkResult {
	if in == nil {
		return nil
	}
	out := new(BenchmarkResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceSpec) DeepCopyInto(out *ComplianceSpec) {
	*out = *in
	out.Attestation = in.Attestation
	out.DataPrivacy = in.DataPrivacy
	if in.RegulatoryFramework != nil {
		in, out := &in.RegulatoryFramework, &out.RegulatoryFramework
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceSpec.
func (in *ComplianceSpec) DeepCopy() *ComplianceSpec {
	if in == nil {
		return nil
	}
	out := new(ComplianceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttestationSpec) DeepCopyInto(out *AttestationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttestationSpec.
func (in *AttestationSpec) DeepCopy() *AttestationSpec {
	if in == nil {
		return nil
	}
	out := new(AttestationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataPrivacySpec) DeepCopyInto(out *DataPrivacySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataPrivacySpec.
func (in *DataPrivacySpec) DeepCopy() *DataPrivacySpec {
	if in == nil {
		return nil
	}
	out := new(DataPrivacySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTrainingTimeMachine) DeepCopyInto(out *FabricTrainingTimeMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTrainingTimeMachine.
func (in *FabricTrainingTimeMachine) DeepCopy() *FabricTrainingTimeMachine {
	if in == nil {
		return nil
	}
	out := new(FabricTrainingTimeMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricTrainingTimeMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTrainingTimeMachineList) DeepCopyInto(out *FabricTrainingTimeMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricTrainingTimeMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTrainingTimeMachineList.
func (in *FabricTrainingTimeMachineList) DeepCopy() *FabricTrainingTimeMachineList {
	if in == nil {
		return nil
	}
	out := new(FabricTrainingTimeMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricTrainingTimeMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTrainingTimeMachineSpec) DeepCopyInto(out *FabricTrainingTimeMachineSpec) {
	*out = *in
	if in.Timeline != nil {
		in, out := &in.Timeline, &out.Timeline
		*out = new(TimelineConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(RetentionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Forks != nil {
		in, out := &in.Forks, &out.Forks
		*out = make([]ForkSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTrainingTimeMachineSpec.
func (in *FabricTrainingTimeMachineSpec) DeepCopy() *FabricTrainingTimeMachineSpec {
	if in == nil {
		return nil
	}
	out := new(FabricTrainingTimeMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTrainingTimeMachineStatus) DeepCopyInto(out *FabricTrainingTimeMachineStatus) {
	*out = *in
	if in.CheckpointTimeline != nil {
		in, out := &in.CheckpointTimeline, &out.CheckpointTimeline
		*out = new(CheckpointTimelineStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Forks != nil {
		in, out := &in.Forks, &out.Forks
		*out = make([]ForkStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTrainingTimeMachineStatus.
func (in *FabricTrainingTimeMachineStatus) DeepCopy() *FabricTrainingTimeMachineStatus {
	if in == nil {
		return nil
	}
	out := new(FabricTrainingTimeMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimelineConfig) DeepCopyInto(out *TimelineConfig) {
	*out = *in
	if in.MetadataPerCheckpoint != nil {
		in, out := &in.MetadataPerCheckpoint, &out.MetadataPerCheckpoint
		*out = make([]CheckpointMetadataField, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimelineConfig.
func (in *TimelineConfig) DeepCopy() *TimelineConfig {
	if in == nil {
		return nil
	}
	out := new(TimelineConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointMetadataField) DeepCopyInto(out *CheckpointMetadataField) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointMetadataField.
func (in *CheckpointMetadataField) DeepCopy() *CheckpointMetadataField {
	if in == nil {
		return nil
	}
	out := new(CheckpointMetadataField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionConfig) DeepCopyInto(out *RetentionConfig) {
	*out = *in
	if in.KeepMilestones != nil {
		in, out := &in.KeepMilestones, &out.KeepMilestones
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionConfig.
func (in *RetentionConfig) DeepCopy() *RetentionConfig {
	if in == nil {
		return nil
	}
	out := new(RetentionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForkSpec) DeepCopyInto(out *ForkSpec) {
	*out = *in
	in.FromCheckpoint.DeepCopyInto(&out.FromCheckpoint)
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(ForkOverrides)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForkSpec.
func (in *ForkSpec) DeepCopy() *ForkSpec {
	if in == nil {
		return nil
	}
	out := new(ForkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointSelector) DeepCopyInto(out *CheckpointSelector) {
	*out = *in
	if in.Step != nil {
		in, out := &in.Step, &out.Step
		*out = new(int)
		**out = **in
	}
	if in.Epoch != nil {
		in, out := &in.Epoch, &out.Epoch
		*out = new(int)
		**out = **in
	}
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(MetricSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointSelector.
func (in *CheckpointSelector) DeepCopy() *CheckpointSelector {
	if in == nil {
		return nil
	}
	out := new(CheckpointSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSelector) DeepCopyInto(out *MetricSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSelector.
func (in *MetricSelector) DeepCopy() *MetricSelector {
	if in == nil {
		return nil
	}
	out := new(MetricSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForkOverrides) DeepCopyInto(out *ForkOverrides) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]EnvOverride, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForkOverrides.
func (in *ForkOverrides) DeepCopy() *ForkOverrides {
	if in == nil {
		return nil
	}
	out := new(ForkOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvOverride) DeepCopyInto(out *EnvOverride) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvOverride.
func (in *EnvOverride) DeepCopy() *EnvOverride {
	if in == nil {
		return nil
	}
	out := new(EnvOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointTimelineStatus) DeepCopyInto(out *CheckpointTimelineStatus) {
	*out = *in
	if in.BestCheckpoint != nil {
		in, out := &in.BestCheckpoint, &out.BestCheckpoint
		*out = new(CheckpointInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.LatestCheckpoint != nil {
		in, out := &in.LatestCheckpoint, &out.LatestCheckpoint
		*out = new(CheckpointInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointTimelineStatus.
func (in *CheckpointTimelineStatus) DeepCopy() *CheckpointTimelineStatus {
	if in == nil {
		return nil
	}
	out := new(CheckpointTimelineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointInfo) DeepCopyInto(out *CheckpointInfo) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointInfo.
func (in *CheckpointInfo) DeepCopy() *CheckpointInfo {
	if in == nil {
		return nil
	}
	out := new(CheckpointInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForkStatus) DeepCopyInto(out *ForkStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForkStatus.
func (in *ForkStatus) DeepCopy() *ForkStatus {
	if in == nil {
		return nil
	}
	out := new(ForkStatus)
	in.DeepCopyInto(out)
	return out
}
