//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostCenterMapping) DeepCopyInto(out *CostCenterMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostCenterMapping.
func (in *CostCenterMapping) DeepCopy() *CostCenterMapping {
	if in == nil {
		return nil
	}
	out := new(CostCenterMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostPerGB) DeepCopyInto(out *CostPerGB) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostPerGB.
func (in *CostPerGB) DeepCopy() *CostPerGB {
	if in == nil {
		return nil
	}
	out := new(CostPerGB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DetectionRule) DeepCopyInto(out *DetectionRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DetectionRule.
func (in *DetectionRule) DeepCopy() *DetectionRule {
	if in == nil {
		return nil
	}
	out := new(DetectionRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAutoPolicy) DeepCopyInto(out *FabricAutoPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAutoPolicy.
func (in *FabricAutoPolicy) DeepCopy() *FabricAutoPolicy {
	if in == nil {
		return nil
	}
	out := new(FabricAutoPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricAutoPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAutoPolicyList) DeepCopyInto(out *FabricAutoPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricAutoPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAutoPolicyList.
func (in *FabricAutoPolicyList) DeepCopy() *FabricAutoPolicyList {
	if in == nil {
		return nil
	}
	out := new(FabricAutoPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricAutoPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAutoPolicySpec) DeepCopyInto(out *FabricAutoPolicySpec) {
	*out = *in
	if in.TargetNamespaces != nil {
		in, out := &in.TargetNamespaces, &out.TargetNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeServices != nil {
		in, out := &in.ExcludeServices, &out.ExcludeServices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAutoPolicySpec.
func (in *FabricAutoPolicySpec) DeepCopy() *FabricAutoPolicySpec {
	if in == nil {
		return nil
	}
	out := new(FabricAutoPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAutoPolicyStatus) DeepCopyInto(out *FabricAutoPolicyStatus) {
	*out = *in
	if in.SuggestedPolicies != nil {
		in, out := &in.SuggestedPolicies, &out.SuggestedPolicies
		*out = make([]SuggestedPolicy, len(*in))
		copy(*out, *in)
	}
	in.LastLearned.DeepCopyInto(&out.LastLearned)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAutoPolicyStatus.
func (in *FabricAutoPolicyStatus) DeepCopy() *FabricAutoPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(FabricAutoPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricFlowPolicy) DeepCopyInto(out *FabricFlowPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricFlowPolicy.
func (in *FabricFlowPolicy) DeepCopy() *FabricFlowPolicy {
	if in == nil {
		return nil
	}
	out := new(FabricFlowPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricFlowPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricFlowPolicyList) DeepCopyInto(out *FabricFlowPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricFlowPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricFlowPolicyList.
func (in *FabricFlowPolicyList) DeepCopy() *FabricFlowPolicyList {
	if in == nil {
		return nil
	}
	out := new(FabricFlowPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricFlowPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricFlowPolicySpec) DeepCopyInto(out *FabricFlowPolicySpec) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(FlowEndpoint)
		(*in).DeepCopyInto(*out)
	}
	if in.Destination != nil {
		in, out := &in.Destination, &out.Destination
		*out = new(FlowEndpoint)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricFlowPolicySpec.
func (in *FabricFlowPolicySpec) DeepCopy() *FabricFlowPolicySpec {
	if in == nil {
		return nil
	}
	out := new(FabricFlowPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricFlowPolicyStatus) DeepCopyInto(out *FabricFlowPolicyStatus) {
	*out = *in
	in.LastApplied.DeepCopyInto(&out.LastApplied)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricFlowPolicyStatus.
func (in *FabricFlowPolicyStatus) DeepCopy() *FabricFlowPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(FabricFlowPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricInferenceInsight) DeepCopyInto(out *FabricInferenceInsight) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricInferenceInsight.
func (in *FabricInferenceInsight) DeepCopy() *FabricInferenceInsight {
	if in == nil {
		return nil
	}
	out := new(FabricInferenceInsight)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricInferenceInsight) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricInferenceInsightList) DeepCopyInto(out *FabricInferenceInsightList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricInferenceInsight, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricInferenceInsightList.
func (in *FabricInferenceInsightList) DeepCopy() *FabricInferenceInsightList {
	if in == nil {
		return nil
	}
	out := new(FabricInferenceInsightList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricInferenceInsightList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricInferenceInsightSpec) DeepCopyInto(out *FabricInferenceInsightSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricInferenceInsightSpec.
func (in *FabricInferenceInsightSpec) DeepCopy() *FabricInferenceInsightSpec {
	if in == nil {
		return nil
	}
	out := new(FabricInferenceInsightSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricInferenceInsightStatus) DeepCopyInto(out *FabricInferenceInsightStatus) {
	*out = *in
	out.LatencyBreakdown = in.LatencyBreakdown
	in.LastAnalysis.DeepCopyInto(&out.LastAnalysis)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricInferenceInsightStatus.
func (in *FabricInferenceInsightStatus) DeepCopy() *FabricInferenceInsightStatus {
	if in == nil {
		return nil
	}
	out := new(FabricInferenceInsightStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricNetworkAnomaly) DeepCopyInto(out *FabricNetworkAnomaly) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricNetworkAnomaly.
func (in *FabricNetworkAnomaly) DeepCopy() *FabricNetworkAnomaly {
	if in == nil {
		return nil
	}
	out := new(FabricNetworkAnomaly)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricNetworkAnomaly) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricNetworkAnomalyList) DeepCopyInto(out *FabricNetworkAnomalyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricNetworkAnomaly, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricNetworkAnomalyList.
func (in *FabricNetworkAnomalyList) DeepCopy() *FabricNetworkAnomalyList {
	if in == nil {
		return nil
	}
	out := new(FabricNetworkAnomalyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricNetworkAnomalyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricNetworkAnomalySpec) DeepCopyInto(out *FabricNetworkAnomalySpec) {
	*out = *in
	if in.DetectionRules != nil {
		in, out := &in.DetectionRules, &out.DetectionRules
		*out = make([]DetectionRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricNetworkAnomalySpec.
func (in *FabricNetworkAnomalySpec) DeepCopy() *FabricNetworkAnomalySpec {
	if in == nil {
		return nil
	}
	out := new(FabricNetworkAnomalySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricNetworkAnomalyStatus) DeepCopyInto(out *FabricNetworkAnomalyStatus) {
	*out = *in
	if in.Anomalies != nil {
		in, out := &in.Anomalies, &out.Anomalies
		*out = make([]NetworkAnomalyEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastCheck.DeepCopyInto(&out.LastCheck)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricNetworkAnomalyStatus.
func (in *FabricNetworkAnomalyStatus) DeepCopy() *FabricNetworkAnomalyStatus {
	if in == nil {
		return nil
	}
	out := new(FabricNetworkAnomalyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricNetworkCost) DeepCopyInto(out *FabricNetworkCost) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricNetworkCost.
func (in *FabricNetworkCost) DeepCopy() *FabricNetworkCost {
	if in == nil {
		return nil
	}
	out := new(FabricNetworkCost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricNetworkCost) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricNetworkCostList) DeepCopyInto(out *FabricNetworkCostList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricNetworkCost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricNetworkCostList.
func (in *FabricNetworkCostList) DeepCopy() *FabricNetworkCostList {
	if in == nil {
		return nil
	}
	out := new(FabricNetworkCostList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricNetworkCostList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricNetworkCostSpec) DeepCopyInto(out *FabricNetworkCostSpec) {
	*out = *in
	if in.TargetNamespaces != nil {
		in, out := &in.TargetNamespaces, &out.TargetNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.CostPerGB = in.CostPerGB
	if in.CostCenters != nil {
		in, out := &in.CostCenters, &out.CostCenters
		*out = make([]CostCenterMapping, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricNetworkCostSpec.
func (in *FabricNetworkCostSpec) DeepCopy() *FabricNetworkCostSpec {
	if in == nil {
		return nil
	}
	out := new(FabricNetworkCostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricNetworkCostStatus) DeepCopyInto(out *FabricNetworkCostStatus) {
	*out = *in
	if in.Reports != nil {
		in, out := &in.Reports, &out.Reports
		*out = make([]NetworkCostReport, len(*in))
		copy(*out, *in)
	}
	in.LastReport.DeepCopyInto(&out.LastReport)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricNetworkCostStatus.
func (in *FabricNetworkCostStatus) DeepCopy() *FabricNetworkCostStatus {
	if in == nil {
		return nil
	}
	out := new(FabricNetworkCostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricSecurityPolicy) DeepCopyInto(out *FabricSecurityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricSecurityPolicy.
func (in *FabricSecurityPolicy) DeepCopy() *FabricSecurityPolicy {
	if in == nil {
		return nil
	}
	out := new(FabricSecurityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricSecurityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricSecurityPolicyList) DeepCopyInto(out *FabricSecurityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricSecurityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricSecurityPolicyList.
func (in *FabricSecurityPolicyList) DeepCopy() *FabricSecurityPolicyList {
	if in == nil {
		return nil
	}
	out := new(FabricSecurityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricSecurityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricSecurityPolicySpec) DeepCopyInto(out *FabricSecurityPolicySpec) {
	*out = *in
	if in.TargetNamespaces != nil {
		in, out := &in.TargetNamespaces, &out.TargetNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DetectionRules != nil {
		in, out := &in.DetectionRules, &out.DetectionRules
		*out = make([]SecurityDetectionRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricSecurityPolicySpec.
func (in *FabricSecurityPolicySpec) DeepCopy() *FabricSecurityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(FabricSecurityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricSecurityPolicyStatus) DeepCopyInto(out *FabricSecurityPolicyStatus) {
	*out = *in
	in.LastAlert.DeepCopyInto(&out.LastAlert)
	if in.DetectionCounts != nil {
		in, out := &in.DetectionCounts, &out.DetectionCounts
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricSecurityPolicyStatus.
func (in *FabricSecurityPolicyStatus) DeepCopy() *FabricSecurityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(FabricSecurityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricServiceGraph) DeepCopyInto(out *FabricServiceGraph) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricServiceGraph.
func (in *FabricServiceGraph) DeepCopy() *FabricServiceGraph {
	if in == nil {
		return nil
	}
	out := new(FabricServiceGraph)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricServiceGraph) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricServiceGraphList) DeepCopyInto(out *FabricServiceGraphList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricServiceGraph, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricServiceGraphList.
func (in *FabricServiceGraphList) DeepCopy() *FabricServiceGraphList {
	if in == nil {
		return nil
	}
	out := new(FabricServiceGraphList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricServiceGraphList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricServiceGraphSpec) DeepCopyInto(out *FabricServiceGraphSpec) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricServiceGraphSpec.
func (in *FabricServiceGraphSpec) DeepCopy() *FabricServiceGraphSpec {
	if in == nil {
		return nil
	}
	out := new(FabricServiceGraphSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricServiceGraphStatus) DeepCopyInto(out *FabricServiceGraphStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]ServiceGraphNode, len(*in))
		copy(*out, *in)
	}
	if in.Edges != nil {
		in, out := &in.Edges, &out.Edges
		*out = make([]ServiceGraphEdge, len(*in))
		copy(*out, *in)
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricServiceGraphStatus.
func (in *FabricServiceGraphStatus) DeepCopy() *FabricServiceGraphStatus {
	if in == nil {
		return nil
	}
	out := new(FabricServiceGraphStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTraceSession) DeepCopyInto(out *FabricTraceSession) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTraceSession.
func (in *FabricTraceSession) DeepCopy() *FabricTraceSession {
	if in == nil {
		return nil
	}
	out := new(FabricTraceSession)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricTraceSession) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTraceSessionList) DeepCopyInto(out *FabricTraceSessionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricTraceSession, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTraceSessionList.
func (in *FabricTraceSessionList) DeepCopy() *FabricTraceSessionList {
	if in == nil {
		return nil
	}
	out := new(FabricTraceSessionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricTraceSessionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTraceSessionSpec) DeepCopyInto(out *FabricTraceSessionSpec) {
	*out = *in
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = new(TraceFilters)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTraceSessionSpec.
func (in *FabricTraceSessionSpec) DeepCopy() *FabricTraceSessionSpec {
	if in == nil {
		return nil
	}
	out := new(FabricTraceSessionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTraceSessionStatus) DeepCopyInto(out *FabricTraceSessionStatus) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.EndTime.DeepCopyInto(&out.EndTime)
	if in.ResultRef != nil {
		in, out := &in.ResultRef, &out.ResultRef
		*out = new(TraceResultRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTraceSessionStatus.
func (in *FabricTraceSessionStatus) DeepCopy() *FabricTraceSessionStatus {
	if in == nil {
		return nil
	}
	out := new(FabricTraceSessionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTrafficInsight) DeepCopyInto(out *FabricTrafficInsight) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTrafficInsight.
func (in *FabricTrafficInsight) DeepCopy() *FabricTrafficInsight {
	if in == nil {
		return nil
	}
	out := new(FabricTrafficInsight)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricTrafficInsight) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTrafficInsightList) DeepCopyInto(out *FabricTrafficInsightList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricTrafficInsight, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTrafficInsightList.
func (in *FabricTrafficInsightList) DeepCopy() *FabricTrafficInsightList {
	if in == nil {
		return nil
	}
	out := new(FabricTrafficInsightList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricTrafficInsightList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTrafficInsightSpec) DeepCopyInto(out *FabricTrafficInsightSpec) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTrafficInsightSpec.
func (in *FabricTrafficInsightSpec) DeepCopy() *FabricTrafficInsightSpec {
	if in == nil {
		return nil
	}
	out := new(FabricTrafficInsightSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTrafficInsightStatus) DeepCopyInto(out *FabricTrafficInsightStatus) {
	*out = *in
	if in.TopTalkers != nil {
		in, out := &in.TopTalkers, &out.TopTalkers
		*out = make([]TopTalker, len(*in))
		copy(*out, *in)
	}
	if in.Anomalies != nil {
		in, out := &in.Anomalies, &out.Anomalies
		*out = make([]TrafficAnomaly, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTrafficInsightStatus.
func (in *FabricTrafficInsightStatus) DeepCopy() *FabricTrafficInsightStatus {
	if in == nil {
		return nil
	}
	out := new(FabricTrafficInsightStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTrainingInsight) DeepCopyInto(out *FabricTrainingInsight) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTrainingInsight.
func (in *FabricTrainingInsight) DeepCopy() *FabricTrainingInsight {
	if in == nil {
		return nil
	}
	out := new(FabricTrainingInsight)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricTrainingInsight) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTrainingInsightList) DeepCopyInto(out *FabricTrainingInsightList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricTrainingInsight, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTrainingInsightList.
func (in *FabricTrainingInsightList) DeepCopy() *FabricTrainingInsightList {
	if in == nil {
		return nil
	}
	out := new(FabricTrainingInsightList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricTrainingInsightList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTrainingInsightSpec) DeepCopyInto(out *FabricTrainingInsightSpec) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTrainingInsightSpec.
func (in *FabricTrainingInsightSpec) DeepCopy() *FabricTrainingInsightSpec {
	if in == nil {
		return nil
	}
	out := new(FabricTrainingInsightSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTrainingInsightStatus) DeepCopyInto(out *FabricTrainingInsightStatus) {
	*out = *in
	if in.RankStats != nil {
		in, out := &in.RankStats, &out.RankStats
		*out = make([]RankStat, len(*in))
		copy(*out, *in)
	}
	if in.Stragglers != nil {
		in, out := &in.Stragglers, &out.Stragglers
		*out = make([]StragglerInfo, len(*in))
		copy(*out, *in)
	}
	in.LastAnalysis.DeepCopyInto(&out.LastAnalysis)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTrainingInsightStatus.
func (in *FabricTrainingInsightStatus) DeepCopy() *FabricTrainingInsightStatus {
	if in == nil {
		return nil
	}
	out := new(FabricTrainingInsightStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowEndpoint) DeepCopyInto(out *FlowEndpoint) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowEndpoint.
func (in *FlowEndpoint) DeepCopy() *FlowEndpoint {
	if in == nil {
		return nil
	}
	out := new(FlowEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LatencyBreakdown) DeepCopyInto(out *LatencyBreakdown) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LatencyBreakdown.
func (in *LatencyBreakdown) DeepCopy() *LatencyBreakdown {
	if in == nil {
		return nil
	}
	out := new(LatencyBreakdown)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkAnomalyEvent) DeepCopyInto(out *NetworkAnomalyEvent) {
	*out = *in
	in.Detected.DeepCopyInto(&out.Detected)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkAnomalyEvent.
func (in *NetworkAnomalyEvent) DeepCopy() *NetworkAnomalyEvent {
	if in == nil {
		return nil
	}
	out := new(NetworkAnomalyEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkCostReport) DeepCopyInto(out *NetworkCostReport) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkCostReport.
func (in *NetworkCostReport) DeepCopy() *NetworkCostReport {
	if in == nil {
		return nil
	}
	out := new(NetworkCostReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RankStat) DeepCopyInto(out *RankStat) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RankStat.
func (in *RankStat) DeepCopy() *RankStat {
	if in == nil {
		return nil
	}
	out := new(RankStat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityDetectionRule) DeepCopyInto(out *SecurityDetectionRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityDetectionRule.
func (in *SecurityDetectionRule) DeepCopy() *SecurityDetectionRule {
	if in == nil {
		return nil
	}
	out := new(SecurityDetectionRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceGraphEdge) DeepCopyInto(out *ServiceGraphEdge) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceGraphEdge.
func (in *ServiceGraphEdge) DeepCopy() *ServiceGraphEdge {
	if in == nil {
		return nil
	}
	out := new(ServiceGraphEdge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceGraphNode) DeepCopyInto(out *ServiceGraphNode) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceGraphNode.
func (in *ServiceGraphNode) DeepCopy() *ServiceGraphNode {
	if in == nil {
		return nil
	}
	out := new(ServiceGraphNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StragglerInfo) DeepCopyInto(out *StragglerInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StragglerInfo.
func (in *StragglerInfo) DeepCopy() *StragglerInfo {
	if in == nil {
		return nil
	}
	out := new(StragglerInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuggestedPolicy) DeepCopyInto(out *SuggestedPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuggestedPolicy.
func (in *SuggestedPolicy) DeepCopy() *SuggestedPolicy {
	if in == nil {
		return nil
	}
	out := new(SuggestedPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopTalker) DeepCopyInto(out *TopTalker) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopTalker.
func (in *TopTalker) DeepCopy() *TopTalker {
	if in == nil {
		return nil
	}
	out := new(TopTalker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceFilters) DeepCopyInto(out *TraceFilters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceFilters.
func (in *TraceFilters) DeepCopy() *TraceFilters {
	if in == nil {
		return nil
	}
	out := new(TraceFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceResultRef) DeepCopyInto(out *TraceResultRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceResultRef.
func (in *TraceResultRef) DeepCopy() *TraceResultRef {
	if in == nil {
		return nil
	}
	out := new(TraceResultRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficAnomaly) DeepCopyInto(out *TrafficAnomaly) {
	*out = *in
	in.Detected.DeepCopyInto(&out.Detected)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficAnomaly.
func (in *TrafficAnomaly) DeepCopy() *TrafficAnomaly {
	if in == nil {
		return nil
	}
	out := new(TrafficAnomaly)
	in.DeepCopyInto(out)
	return out
}
