//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostCenterMapping) DeepCopyInto(out *CostCenterMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostCenterMapping.
func (in *CostCenterMapping) DeepCopy() *CostCenterMapping {
	if in == nil {
		return nil
	}
	out := new(CostCenterMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostPerGB) DeepCopyInto(out *CostPerGB) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostPerGB.
func (in *CostPerGB) DeepCopy() *CostPerGB {
	if in == nil {
		return nil
	}
	out := new(CostPerGB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DetectionRule) DeepCopyInto(out *DetectionRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DetectionRule.
func (in *DetectionRule) DeepCopy() *DetectionRule {
	if in == nil {
		return nil
	}
	out := new(DetectionRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaAutoPolicy) DeepCopyInto(out *GryviaAutoPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaAutoPolicy.
func (in *GryviaAutoPolicy) DeepCopy() *GryviaAutoPolicy {
	if in == nil {
		return nil
	}
	out := new(GryviaAutoPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaAutoPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaAutoPolicyList) DeepCopyInto(out *GryviaAutoPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaAutoPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaAutoPolicyList.
func (in *GryviaAutoPolicyList) DeepCopy() *GryviaAutoPolicyList {
	if in == nil {
		return nil
	}
	out := new(GryviaAutoPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaAutoPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaAutoPolicySpec) DeepCopyInto(out *GryviaAutoPolicySpec) {
	*out = *in
	if in.TargetNamespaces != nil {
		in, out := &in.TargetNamespaces, &out.TargetNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeServices != nil {
		in, out := &in.ExcludeServices, &out.ExcludeServices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaAutoPolicySpec.
func (in *GryviaAutoPolicySpec) DeepCopy() *GryviaAutoPolicySpec {
	if in == nil {
		return nil
	}
	out := new(GryviaAutoPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaAutoPolicyStatus) DeepCopyInto(out *GryviaAutoPolicyStatus) {
	*out = *in
	if in.SuggestedPolicies != nil {
		in, out := &in.SuggestedPolicies, &out.SuggestedPolicies
		*out = make([]SuggestedPolicy, len(*in))
		copy(*out, *in)
	}
	in.LastLearned.DeepCopyInto(&out.LastLearned)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaAutoPolicyStatus.
func (in *GryviaAutoPolicyStatus) DeepCopy() *GryviaAutoPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaAutoPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaFlowPolicy) DeepCopyInto(out *GryviaFlowPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaFlowPolicy.
func (in *GryviaFlowPolicy) DeepCopy() *GryviaFlowPolicy {
	if in == nil {
		return nil
	}
	out := new(GryviaFlowPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaFlowPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaFlowPolicyList) DeepCopyInto(out *GryviaFlowPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaFlowPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaFlowPolicyList.
func (in *GryviaFlowPolicyList) DeepCopy() *GryviaFlowPolicyList {
	if in == nil {
		return nil
	}
	out := new(GryviaFlowPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaFlowPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaFlowPolicySpec) DeepCopyInto(out *GryviaFlowPolicySpec) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(FlowEndpoint)
		(*in).DeepCopyInto(*out)
	}
	if in.Destination != nil {
		in, out := &in.Destination, &out.Destination
		*out = new(FlowEndpoint)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaFlowPolicySpec.
func (in *GryviaFlowPolicySpec) DeepCopy() *GryviaFlowPolicySpec {
	if in == nil {
		return nil
	}
	out := new(GryviaFlowPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaFlowPolicyStatus) DeepCopyInto(out *GryviaFlowPolicyStatus) {
	*out = *in
	in.LastApplied.DeepCopyInto(&out.LastApplied)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaFlowPolicyStatus.
func (in *GryviaFlowPolicyStatus) DeepCopy() *GryviaFlowPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaFlowPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaInferenceInsight) DeepCopyInto(out *GryviaInferenceInsight) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaInferenceInsight.
func (in *GryviaInferenceInsight) DeepCopy() *GryviaInferenceInsight {
	if in == nil {
		return nil
	}
	out := new(GryviaInferenceInsight)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaInferenceInsight) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaInferenceInsightList) DeepCopyInto(out *GryviaInferenceInsightList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaInferenceInsight, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaInferenceInsightList.
func (in *GryviaInferenceInsightList) DeepCopy() *GryviaInferenceInsightList {
	if in == nil {
		return nil
	}
	out := new(GryviaInferenceInsightList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaInferenceInsightList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaInferenceInsightSpec) DeepCopyInto(out *GryviaInferenceInsightSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaInferenceInsightSpec.
func (in *GryviaInferenceInsightSpec) DeepCopy() *GryviaInferenceInsightSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaInferenceInsightSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaInferenceInsightStatus) DeepCopyInto(out *GryviaInferenceInsightStatus) {
	*out = *in
	out.LatencyBreakdown = in.LatencyBreakdown
	in.LastAnalysis.DeepCopyInto(&out.LastAnalysis)
	if in.TTFTP99Ms != nil {
		in, out := &in.TTFTP99Ms, &out.TTFTP99Ms
		*out = new(float64)
		**out = **in
	}
	if in.ITLP99Ms != nil {
		in, out := &in.ITLP99Ms, &out.ITLP99Ms
		*out = new(float64)
		**out = **in
	}
	if in.QueueTimeP99Ms != nil {
		in, out := &in.QueueTimeP99Ms, &out.QueueTimeP99Ms
		*out = new(float64)
		**out = **in
	}
	if in.E2EP99Ms != nil {
		in, out := &in.E2EP99Ms, &out.E2EP99Ms
		*out = new(float64)
		**out = **in
	}
	if in.RequestsWaiting != nil {
		in, out := &in.RequestsWaiting, &out.RequestsWaiting
		*out = new(int64)
		**out = **in
	}
	if in.KVCacheUsage != nil {
		in, out := &in.KVCacheUsage, &out.KVCacheUsage
		*out = new(float64)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaInferenceInsightStatus.
func (in *GryviaInferenceInsightStatus) DeepCopy() *GryviaInferenceInsightStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaInferenceInsightStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaNetworkAnomaly) DeepCopyInto(out *GryviaNetworkAnomaly) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaNetworkAnomaly.
func (in *GryviaNetworkAnomaly) DeepCopy() *GryviaNetworkAnomaly {
	if in == nil {
		return nil
	}
	out := new(GryviaNetworkAnomaly)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaNetworkAnomaly) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaNetworkAnomalyList) DeepCopyInto(out *GryviaNetworkAnomalyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaNetworkAnomaly, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaNetworkAnomalyList.
func (in *GryviaNetworkAnomalyList) DeepCopy() *GryviaNetworkAnomalyList {
	if in == nil {
		return nil
	}
	out := new(GryviaNetworkAnomalyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaNetworkAnomalyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaNetworkAnomalySpec) DeepCopyInto(out *GryviaNetworkAnomalySpec) {
	*out = *in
	if in.DetectionRules != nil {
		in, out := &in.DetectionRules, &out.DetectionRules
		*out = make([]DetectionRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaNetworkAnomalySpec.
func (in *GryviaNetworkAnomalySpec) DeepCopy() *GryviaNetworkAnomalySpec {
	if in == nil {
		return nil
	}
	out := new(GryviaNetworkAnomalySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaNetworkAnomalyStatus) DeepCopyInto(out *GryviaNetworkAnomalyStatus) {
	*out = *in
	if in.Anomalies != nil {
		in, out := &in.Anomalies, &out.Anomalies
		*out = make([]NetworkAnomalyEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastCheck.DeepCopyInto(&out.LastCheck)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaNetworkAnomalyStatus.
func (in *GryviaNetworkAnomalyStatus) DeepCopy() *GryviaNetworkAnomalyStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaNetworkAnomalyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaNetworkCost) DeepCopyInto(out *GryviaNetworkCost) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaNetworkCost.
func (in *GryviaNetworkCost) DeepCopy() *GryviaNetworkCost {
	if in == nil {
		return nil
	}
	out := new(GryviaNetworkCost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaNetworkCost) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaNetworkCostList) DeepCopyInto(out *GryviaNetworkCostList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaNetworkCost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaNetworkCostList.
func (in *GryviaNetworkCostList) DeepCopy() *GryviaNetworkCostList {
	if in == nil {
		return nil
	}
	out := new(GryviaNetworkCostList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaNetworkCostList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaNetworkCostSpec) DeepCopyInto(out *GryviaNetworkCostSpec) {
	*out = *in
	if in.TargetNamespaces != nil {
		in, out := &in.TargetNamespaces, &out.TargetNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.CostPerGB = in.CostPerGB
	if in.CostCenters != nil {
		in, out := &in.CostCenters, &out.CostCenters
		*out = make([]CostCenterMapping, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaNetworkCostSpec.
func (in *GryviaNetworkCostSpec) DeepCopy() *GryviaNetworkCostSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaNetworkCostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaNetworkCostStatus) DeepCopyInto(out *GryviaNetworkCostStatus) {
	*out = *in
	if in.Reports != nil {
		in, out := &in.Reports, &out.Reports
		*out = make([]NetworkCostReport, len(*in))
		copy(*out, *in)
	}
	in.LastReport.DeepCopyInto(&out.LastReport)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaNetworkCostStatus.
func (in *GryviaNetworkCostStatus) DeepCopy() *GryviaNetworkCostStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaNetworkCostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaSecurityPolicy) DeepCopyInto(out *GryviaSecurityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaSecurityPolicy.
func (in *GryviaSecurityPolicy) DeepCopy() *GryviaSecurityPolicy {
	if in == nil {
		return nil
	}
	out := new(GryviaSecurityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaSecurityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaSecurityPolicyList) DeepCopyInto(out *GryviaSecurityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaSecurityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaSecurityPolicyList.
func (in *GryviaSecurityPolicyList) DeepCopy() *GryviaSecurityPolicyList {
	if in == nil {
		return nil
	}
	out := new(GryviaSecurityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaSecurityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaSecurityPolicySpec) DeepCopyInto(out *GryviaSecurityPolicySpec) {
	*out = *in
	if in.TargetNamespaces != nil {
		in, out := &in.TargetNamespaces, &out.TargetNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DetectionRules != nil {
		in, out := &in.DetectionRules, &out.DetectionRules
		*out = make([]SecurityDetectionRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaSecurityPolicySpec.
func (in *GryviaSecurityPolicySpec) DeepCopy() *GryviaSecurityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(GryviaSecurityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaSecurityPolicyStatus) DeepCopyInto(out *GryviaSecurityPolicyStatus) {
	*out = *in
	in.LastAlert.DeepCopyInto(&out.LastAlert)
	if in.DetectionCounts != nil {
		in, out := &in.DetectionCounts, &out.DetectionCounts
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaSecurityPolicyStatus.
func (in *GryviaSecurityPolicyStatus) DeepCopy() *GryviaSecurityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaSecurityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaServiceGraph) DeepCopyInto(out *GryviaServiceGraph) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaServiceGraph.
func (in *GryviaServiceGraph) DeepCopy() *GryviaServiceGraph {
	if in == nil {
		return nil
	}
	out := new(GryviaServiceGraph)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaServiceGraph) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaServiceGraphList) DeepCopyInto(out *GryviaServiceGraphList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaServiceGraph, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaServiceGraphList.
func (in *GryviaServiceGraphList) DeepCopy() *GryviaServiceGraphList {
	if in == nil {
		return nil
	}
	out := new(GryviaServiceGraphList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaServiceGraphList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaServiceGraphSpec) DeepCopyInto(out *GryviaServiceGraphSpec) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaServiceGraphSpec.
func (in *GryviaServiceGraphSpec) DeepCopy() *GryviaServiceGraphSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaServiceGraphSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaServiceGraphStatus) DeepCopyInto(out *GryviaServiceGraphStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]ServiceGraphNode, len(*in))
		copy(*out, *in)
	}
	if in.Edges != nil {
		in, out := &in.Edges, &out.Edges
		*out = make([]ServiceGraphEdge, len(*in))
		copy(*out, *in)
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaServiceGraphStatus.
func (in *GryviaServiceGraphStatus) DeepCopy() *GryviaServiceGraphStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaServiceGraphStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaTraceSession) DeepCopyInto(out *GryviaTraceSession) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaTraceSession.
func (in *GryviaTraceSession) DeepCopy() *GryviaTraceSession {
	if in == nil {
		return nil
	}
	out := new(GryviaTraceSession)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaTraceSession) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaTraceSessionList) DeepCopyInto(out *GryviaTraceSessionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaTraceSession, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaTraceSessionList.
func (in *GryviaTraceSessionList) DeepCopy() *GryviaTraceSessionList {
	if in == nil {
		return nil
	}
	out := new(GryviaTraceSessionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaTraceSessionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaTraceSessionSpec) DeepCopyInto(out *GryviaTraceSessionSpec) {
	*out = *in
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = new(TraceFilters)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaTraceSessionSpec.
func (in *GryviaTraceSessionSpec) DeepCopy() *GryviaTraceSessionSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaTraceSessionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaTraceSessionStatus) DeepCopyInto(out *GryviaTraceSessionStatus) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.EndTime.DeepCopyInto(&out.EndTime)
	if in.ResultRef != nil {
		in, out := &in.ResultRef, &out.ResultRef
		*out = new(TraceResultRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaTraceSessionStatus.
func (in *GryviaTraceSessionStatus) DeepCopy() *GryviaTraceSessionStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaTraceSessionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaTrafficInsight) DeepCopyInto(out *GryviaTrafficInsight) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaTrafficInsight.
func (in *GryviaTrafficInsight) DeepCopy() *GryviaTrafficInsight {
	if in == nil {
		return nil
	}
	out := new(GryviaTrafficInsight)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaTrafficInsight) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaTrafficInsightList) DeepCopyInto(out *GryviaTrafficInsightList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaTrafficInsight, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaTrafficInsightList.
func (in *GryviaTrafficInsightList) DeepCopy() *GryviaTrafficInsightList {
	if in == nil {
		return nil
	}
	out := new(GryviaTrafficInsightList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaTrafficInsightList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaTrafficInsightSpec) DeepCopyInto(out *GryviaTrafficInsightSpec) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaTrafficInsightSpec.
func (in *GryviaTrafficInsightSpec) DeepCopy() *GryviaTrafficInsightSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaTrafficInsightSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaTrafficInsightStatus) DeepCopyInto(out *GryviaTrafficInsightStatus) {
	*out = *in
	if in.TopTalkers != nil {
		in, out := &in.TopTalkers, &out.TopTalkers
		*out = make([]TopTalker, len(*in))
		copy(*out, *in)
	}
	if in.Anomalies != nil {
		in, out := &in.Anomalies, &out.Anomalies
		*out = make([]TrafficAnomaly, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaTrafficInsightStatus.
func (in *GryviaTrafficInsightStatus) DeepCopy() *GryviaTrafficInsightStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaTrafficInsightStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaTrainingInsight) DeepCopyInto(out *GryviaTrainingInsight) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaTrainingInsight.
func (in *GryviaTrainingInsight) DeepCopy() *GryviaTrainingInsight {
	if in == nil {
		return nil
	}
	out := new(GryviaTrainingInsight)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaTrainingInsight) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaTrainingInsightList) DeepCopyInto(out *GryviaTrainingInsightList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GryviaTrainingInsight, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaTrainingInsightList.
func (in *GryviaTrainingInsightList) DeepCopy() *GryviaTrainingInsightList {
	if in == nil {
		return nil
	}
	out := new(GryviaTrainingInsightList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GryviaTrainingInsightList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaTrainingInsightSpec) DeepCopyInto(out *GryviaTrainingInsightSpec) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaTrainingInsightSpec.
func (in *GryviaTrainingInsightSpec) DeepCopy() *GryviaTrainingInsightSpec {
	if in == nil {
		return nil
	}
	out := new(GryviaTrainingInsightSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GryviaTrainingInsightStatus) DeepCopyInto(out *GryviaTrainingInsightStatus) {
	*out = *in
	if in.RankStats != nil {
		in, out := &in.RankStats, &out.RankStats
		*out = make([]RankStat, len(*in))
		copy(*out, *in)
	}
	if in.Stragglers != nil {
		in, out := &in.Stragglers, &out.Stragglers
		*out = make([]StragglerInfo, len(*in))
		copy(*out, *in)
	}
	in.LastAnalysis.DeepCopyInto(&out.LastAnalysis)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GryviaTrainingInsightStatus.
func (in *GryviaTrainingInsightStatus) DeepCopy() *GryviaTrainingInsightStatus {
	if in == nil {
		return nil
	}
	out := new(GryviaTrainingInsightStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowEndpoint) DeepCopyInto(out *FlowEndpoint) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowEndpoint.
func (in *FlowEndpoint) DeepCopy() *FlowEndpoint {
	if in == nil {
		return nil
	}
	out := new(FlowEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LatencyBreakdown) DeepCopyInto(out *LatencyBreakdown) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LatencyBreakdown.
func (in *LatencyBreakdown) DeepCopy() *LatencyBreakdown {
	if in == nil {
		return nil
	}
	out := new(LatencyBreakdown)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkAnomalyEvent) DeepCopyInto(out *NetworkAnomalyEvent) {
	*out = *in
	in.Detected.DeepCopyInto(&out.Detected)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkAnomalyEvent.
func (in *NetworkAnomalyEvent) DeepCopy() *NetworkAnomalyEvent {
	if in == nil {
		return nil
	}
	out := new(NetworkAnomalyEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkCostReport) DeepCopyInto(out *NetworkCostReport) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkCostReport.
func (in *NetworkCostReport) DeepCopy() *NetworkCostReport {
	if in == nil {
		return nil
	}
	out := new(NetworkCostReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RankStat) DeepCopyInto(out *RankStat) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RankStat.
func (in *RankStat) DeepCopy() *RankStat {
	if in == nil {
		return nil
	}
	out := new(RankStat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityDetectionRule) DeepCopyInto(out *SecurityDetectionRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityDetectionRule.
func (in *SecurityDetectionRule) DeepCopy() *SecurityDetectionRule {
	if in == nil {
		return nil
	}
	out := new(SecurityDetectionRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceGraphEdge) DeepCopyInto(out *ServiceGraphEdge) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceGraphEdge.
func (in *ServiceGraphEdge) DeepCopy() *ServiceGraphEdge {
	if in == nil {
		return nil
	}
	out := new(ServiceGraphEdge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceGraphNode) DeepCopyInto(out *ServiceGraphNode) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceGraphNode.
func (in *ServiceGraphNode) DeepCopy() *ServiceGraphNode {
	if in == nil {
		return nil
	}
	out := new(ServiceGraphNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StragglerInfo) DeepCopyInto(out *StragglerInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StragglerInfo.
func (in *StragglerInfo) DeepCopy() *StragglerInfo {
	if in == nil {
		return nil
	}
	out := new(StragglerInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuggestedPolicy) DeepCopyInto(out *SuggestedPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuggestedPolicy.
func (in *SuggestedPolicy) DeepCopy() *SuggestedPolicy {
	if in == nil {
		return nil
	}
	out := new(SuggestedPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopTalker) DeepCopyInto(out *TopTalker) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopTalker.
func (in *TopTalker) DeepCopy() *TopTalker {
	if in == nil {
		return nil
	}
	out := new(TopTalker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceFilters) DeepCopyInto(out *TraceFilters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceFilters.
func (in *TraceFilters) DeepCopy() *TraceFilters {
	if in == nil {
		return nil
	}
	out := new(TraceFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceResultRef) DeepCopyInto(out *TraceResultRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceResultRef.
func (in *TraceResultRef) DeepCopy() *TraceResultRef {
	if in == nil {
		return nil
	}
	out := new(TraceResultRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficAnomaly) DeepCopyInto(out *TrafficAnomaly) {
	*out = *in
	in.Detected.DeepCopyInto(&out.Detected)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficAnomaly.
func (in *TrafficAnomaly) DeepCopy() *TrafficAnomaly {
	if in == nil {
		return nil
	}
	out := new(TrafficAnomaly)
	in.DeepCopyInto(out)
	return out
}
