package inference

import (
	"reflect"
	"testing"
	"time"
)

var t0 = time.Unix(1_800_000_000, 0)

func near(t *testing.T, name string, got *float64, want float64) {
	t.Helper()
	if got == nil {
		t.Errorf("%s: not measured, want %v", name, want)
		return
	}
	if d := *got - want; d > 1e-6 || d < -1e-6 {
		t.Errorf("%s = %v, want %v", name, *got, want)
	}
}

func unmeasured(t *testing.T, name string, got *float64) {
	t.Helper()
	if got != nil {
		t.Errorf("%s = %v, want not measured", name, *got)
	}
}

// The fixtures in testdata/ are hand-authored (generated by a script from the metric names and
// label sets documented by each engine), NOT captured from a live engine. The expected numbers
// below were worked out by hand from the per-interval bucket deltas.

func TestVLLMv0(t *testing.T) {
	e, _ := NewEngine("vllm", 0)
	if !e.Detect(mustParseFile(t, "vllm_v0_t0.txt")) {
		t.Fatal("detect")
	}
	r0 := e.Observe(t0, mustParseFile(t, "vllm_v0_t0.txt"))
	unmeasured(t, "ttft after baseline", r0.TTFTP99)
	// Gauges are instantaneous: available immediately.
	near(t, "waiting", r0.Waiting, 3)
	near(t, "running", r0.Running, 12)
	near(t, "kv", r0.KVCache, 0.42)

	r := e.Observe(t0.Add(15*time.Second), mustParseFile(t, "vllm_v0_t1.txt"))
	// 100 new requests: cumulative 80 <= 0.1s, 90 <= 0.25s, 100 <= 0.5s; rank 99 => 0.25+0.25*9/10.
	near(t, "ttft p99 ms", r.TTFTP99, 475)
	// 1000 new tokens: cumulative 950 <= 0.05, 995 <= 0.075; rank 990 => 0.05+0.025*40/45.
	near(t, "itl p99 ms", r.ITLP99, 72.2222222222)
	// 100 new: 98 <= 2.0s, 100 <= 2.5s; rank 99 => 2.25.
	near(t, "e2e p99 ms", r.E2EP99, 2250)
	// 100 new: 98 <= 0.04, 100 <= 0.06; rank 99 => 0.05.
	near(t, "queue p99 ms", r.QueueP99, 50)
	near(t, "kv", r.KVCache, 0.42)
	if r.Engine != "vllm" || !r.At.Equal(t0.Add(15*time.Second)) {
		t.Errorf("engine/at = %v %v", r.Engine, r.At)
	}
	// v0 has no prefill/decode histograms: reported missing, never a zero.
	unmeasured(t, "prefill", r.PrefillP99)
	unmeasured(t, "decode", r.DecodeP99)
	if !reflect.DeepEqual(r.Missing, []string{"decode", "prefill"}) {
		t.Errorf("missing = %v", r.Missing)
	}
	wantAvail := []string{"e2e", "itl", "kv_cache", "queue_time", "requests_running", "requests_waiting", "ttft"}
	if !reflect.DeepEqual(r.Available, wantAvail) {
		t.Errorf("available = %v", r.Available)
	}
}

func TestVLLMv1RenamedMetricsAndPrefillDecode(t *testing.T) {
	e := newVLLM(DefaultWindow)
	e.Observe(t0, mustParseFile(t, "vllm_v1_t0.txt"))
	r := e.Observe(t0.Add(15*time.Second), mustParseFile(t, "vllm_v1_t1.txt"))
	near(t, "itl (inter_token_latency_seconds)", r.ITLP99, 72.2222222222)
	near(t, "kv (kv_cache_usage_perc)", r.KVCache, 0.42)
	// 20 new: 5 <= 0.04, 15 <= 0.06, 20 <= 0.08; rank 19.8 => 0.06+0.02*4.8/5.
	near(t, "prefill p99 ms", r.PrefillP99, 79.2)
	// 20 new: 5 <= 0.75, 15 <= 1.0, 20 <= 2.5; rank 19.8 => 1.0+1.5*4.8/5.
	near(t, "decode p99 ms", r.DecodeP99, 2440)
	if len(r.Missing) != 0 {
		t.Errorf("missing = %v", r.Missing)
	}
}

func TestVLLMEngineRestartRebaselines(t *testing.T) {
	e := newVLLM(DefaultWindow)
	e.Observe(t0, mustParseFile(t, "vllm_v0_t1.txt"))
	// The engine restarted: counters went back to the (smaller) t0 values.
	r := e.Observe(t0.Add(15*time.Second), mustParseFile(t, "vllm_v0_t0.txt"))
	unmeasured(t, "ttft right after a reset", r.TTFTP99)
	// And the next interval is measured from the new baseline.
	r = e.Observe(t0.Add(30*time.Second), mustParseFile(t, "vllm_v0_t1.txt"))
	near(t, "ttft after reset", r.TTFTP99, 475)
}

func TestTritonCountersGiveMeansNotP99(t *testing.T) {
	e, _ := NewEngine("triton", 0)
	if !e.Detect(mustParseFile(t, "triton_t0.txt")) {
		t.Fatal("detect")
	}
	e.Observe(t0, mustParseFile(t, "triton_t0.txt"))
	r := e.Observe(t0.Add(15*time.Second), mustParseFile(t, "triton_t1.txt"))
	// 500 new requests, 3.7e6 us request time, 4.3e5 us queue time; 210 executions, 2.415e6 us compute.
	near(t, "e2e mean ms", r.E2EMean, 7.4)
	near(t, "queue mean ms", r.QueueMean, 0.86)
	near(t, "compute mean ms (per execution)", r.ComputeMean, 11.5)
	unmeasured(t, "e2e p99", r.E2EP99)
	unmeasured(t, "queue p99", r.QueueP99)
	near(t, "pending (waiting)", r.Waiting, 6)
	unmeasured(t, "ttft", r.TTFTP99)
	unmeasured(t, "itl", r.ITLP99)
	unmeasured(t, "kv", r.KVCache)
	for _, k := range []string{"ttft", "itl", "kv_cache"} {
		if !contains(r.Missing, k) {
			t.Errorf("%s should be reported missing: %v", k, r.Missing)
		}
	}
	if len(r.Notes) == 0 {
		t.Error("expected a note that the latencies are means")
	}
}

func TestTritonSummariesGiveRealP99(t *testing.T) {
	e := newTriton(DefaultWindow)
	e.Observe(t0, mustParseFile(t, "triton_summary_t0.txt"))
	r := e.Observe(t0.Add(15*time.Second), mustParseFile(t, "triton_summary_t1.txt"))
	// Worst model: 21000 us request, 900 us queue.
	near(t, "e2e p99 ms", r.E2EP99, 21)
	near(t, "queue p99 ms", r.QueueP99, 0.9)
	near(t, "e2e mean ms", r.E2EMean, 7.4)
	for _, n := range r.Notes {
		if n != "compute: mean per model execution (batch), not per request" {
			t.Errorf("unexpected note %q", n)
		}
	}
}

func TestTGI(t *testing.T) {
	e, _ := NewEngine("tgi", 0)
	if !e.Detect(mustParseFile(t, "tgi_t0.txt")) {
		t.Fatal("detect")
	}
	e.Observe(t0, mustParseFile(t, "tgi_t0.txt"))
	r := e.Observe(t0.Add(15*time.Second), mustParseFile(t, "tgi_t1.txt"))
	// queue: 98 <= 0.02, 100 <= 0.05; rank 99 => 0.02+0.03*1/2.
	near(t, "queue p99 ms", r.QueueP99, 35)
	// mean time per token: 98 <= 0.1, 100 <= 0.15; rank 99 => 0.1+0.05*1/2.
	near(t, "itl p99 ms (p99 of per-request means)", r.ITLP99, 125)
	// request duration: 98 <= 10, 100 <= 20 => 15 s.
	near(t, "e2e p99 ms", r.E2EP99, 15000)
	near(t, "waiting (tgi_queue_size)", r.Waiting, 7)
	near(t, "running (tgi_batch_current_size)", r.Running, 4)
	unmeasured(t, "ttft", r.TTFTP99)
	unmeasured(t, "kv", r.KVCache)
	if !contains(r.Missing, "ttft") || !contains(r.Missing, "kv_cache") {
		t.Errorf("missing = %v", r.Missing)
	}
	if len(r.Notes) != 1 {
		t.Errorf("notes = %v", r.Notes)
	}
}

func TestDetectEngine(t *testing.T) {
	for file, want := range map[string]string{
		"vllm_v1_t0.txt": "vllm", "triton_t0.txt": "triton", "tgi_t0.txt": "tgi",
	} {
		if got := DetectEngine(mustParseFile(t, file)); got != want {
			t.Errorf("%s: %q want %q", file, got, want)
		}
	}
	if DetectEngine(Families{"process_cpu_seconds_total": {}}) != "" {
		t.Error("unknown exposition")
	}
	if _, err := NewEngine("sglang", 0); err == nil {
		t.Error("unknown engine name")
	}
}

func TestWrongEngineExposesNothing(t *testing.T) {
	// A vLLM parser pointed at a Triton endpoint finds nothing rather than inventing zeros.
	r := newVLLM(DefaultWindow).Observe(t0, mustParseFile(t, "triton_t0.txt"))
	if len(r.Available) != 0 || r.Waiting != nil || r.KVCache != nil {
		t.Errorf("reading = %+v", r)
	}
}

func contains(s []string, v string) bool {
	for _, x := range s {
		if x == v {
			return true
		}
	}
	return false
}
