{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "network-intelligence.operatorServiceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "network-intelligence.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
  {{- with .Values.serviceAccount.operator.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "network-intelligence.collectorServiceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "network-intelligence.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
  {{- with .Values.serviceAccount.collector.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
