{{- if .Values.dcgmExporter.enabled }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dcgm-exporter
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "kubefabric.labels" . | nindent 4 }}
    app.kubernetes.io/component: dcgm-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: dcgm-exporter
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: dcgm-exporter
    spec:
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: dcgm-exporter
          image: "{{ .Values.dcgmExporter.image.repository }}:{{ .Values.dcgmExporter.image.tag }}"
          imagePullPolicy: {{ .Values.dcgmExporter.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9400
              protocol: TCP
          securityContext:
            privileged: true
          volumeMounts:
            - name: pod-gpu-resources
              mountPath: /var/lib/kubelet/pod-resources
              readOnly: true
      volumes:
        - name: pod-gpu-resources
          hostPath:
            path: /var/lib/kubelet/pod-resources

---
apiVersion: v1
kind: Service
metadata:
  name: dcgm-exporter
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "kubefabric.labels" . | nindent 4 }}
    app.kubernetes.io/component: dcgm-exporter
spec:
  type: {{ .Values.dcgmExporter.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.dcgmExporter.service.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/component: dcgm-exporter
{{- end }}
