#!/usr/bin/env python3
"""Generate the CRD reference page from crds/*.yaml so it cannot drift from the real schemas.

Usage: python3 scripts/gen-crd-docs.py   (writes website/docs/reference/crds.md)
"""
import glob
import os
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "website", "docs", "reference", "crds.md")


def main() -> int:
    crds = []
    for path in sorted(glob.glob(os.path.join(ROOT, "crds", "*.yaml"))):
        with open(path) as fh:
            crds.append(yaml.safe_load(fh))
    crds.sort(key=lambda c: c["spec"]["names"]["kind"])

    lines = [
        "---",
        "title: CRD reference",
        "---",
        "",
        "# CRD reference",
        "",
        "<!-- Generated by scripts/gen-crd-docs.py from crds/*.yaml. Do not edit by hand. -->",
        "",
        f"Gryvia defines {len(crds)} custom resources in the `gryvia.io` API group (version `v1`, alpha: fields may change "
        "between releases). Full schemas are in [`crds/`](https://github.com/zyvorai/gryvia/tree/main/crds); "
        "`kubectl explain <kind>.spec` works on any cluster with Gryvia installed.",
        "",
        "| Kind | Resource | Scope | Required spec fields | Other spec fields |",
        "|------|----------|-------|----------------------|-------------------|",
    ]
    for crd in crds:
        names = crd["spec"]["names"]
        version = crd["spec"]["versions"][0]
        schema = version["schema"]["openAPIV3Schema"]
        spec = schema.get("properties", {}).get("spec", {})
        required = ", ".join(f"`{r}`" for r in spec.get("required", [])) or "none"
        others = [k for k in spec.get("properties", {}) if k not in spec.get("required", [])]
        more = ", ".join(f"`{k}`" for k in others[:8]) + (", …" if len(others) > 8 else "")
        lines.append(f"| `{names['kind']}` | `{names['plural']}` | {crd['spec']['scope']} | {required} | {more or '—'} |")
    lines.append("")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {os.path.relpath(OUT, ROOT)} ({len(crds)} kinds)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
