//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetSpec) DeepCopyInto(out *BudgetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetSpec.
func (in *BudgetSpec) DeepCopy() *BudgetSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetStatus) DeepCopyInto(out *BudgetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetStatus.
func (in *BudgetStatus) DeepCopy() *BudgetStatus {
	if in == nil {
		return nil
	}
	out := new(BudgetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAIJob) DeepCopyInto(out *FabricAIJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAIJob.
func (in *FabricAIJob) DeepCopy() *FabricAIJob {
	if in == nil {
		return nil
	}
	out := new(FabricAIJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricAIJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAIJobList) DeepCopyInto(out *FabricAIJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricAIJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAIJobList.
func (in *FabricAIJobList) DeepCopy() *FabricAIJobList {
	if in == nil {
		return nil
	}
	out := new(FabricAIJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricAIJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAIJobSpec) DeepCopyInto(out *FabricAIJobSpec) {
	*out = *in
	if in.Distributed != nil {
		in, out := &in.Distributed, &out.Distributed
		*out = new(FabricAIJobDistributedSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAIJobSpec.
func (in *FabricAIJobSpec) DeepCopy() *FabricAIJobSpec {
	if in == nil {
		return nil
	}
	out := new(FabricAIJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAIJobDistributedSpec) DeepCopyInto(out *FabricAIJobDistributedSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAIJobDistributedSpec.
func (in *FabricAIJobDistributedSpec) DeepCopy() *FabricAIJobDistributedSpec {
	if in == nil {
		return nil
	}
	out := new(FabricAIJobDistributedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAIJobStatus) DeepCopyInto(out *FabricAIJobStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodesAllocated != nil {
		in, out := &in.NodesAllocated, &out.NodesAllocated
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAIJobStatus.
func (in *FabricAIJobStatus) DeepCopy() *FabricAIJobStatus {
	if in == nil {
		return nil
	}
	out := new(FabricAIJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricQuota) DeepCopyInto(out *FabricQuota) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricQuota.
func (in *FabricQuota) DeepCopy() *FabricQuota {
	if in == nil {
		return nil
	}
	out := new(FabricQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricQuota) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricQuotaList) DeepCopyInto(out *FabricQuotaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricQuota, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricQuotaList.
func (in *FabricQuotaList) DeepCopy() *FabricQuotaList {
	if in == nil {
		return nil
	}
	out := new(FabricQuotaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricQuotaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricQuotaSpec) DeepCopyInto(out *FabricQuotaSpec) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.GPUQuota.DeepCopyInto(&out.GPUQuota)
	if in.Budget != nil {
		in, out := &in.Budget, &out.Budget
		*out = new(BudgetSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricQuotaSpec.
func (in *FabricQuotaSpec) DeepCopy() *FabricQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(FabricQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricQuotaStatus) DeepCopyInto(out *FabricQuotaStatus) {
	*out = *in
	out.CurrentUsage = in.CurrentUsage
	if in.BudgetStatus != nil {
		in, out := &in.BudgetStatus, &out.BudgetStatus
		*out = new(BudgetStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricQuotaStatus.
func (in *FabricQuotaStatus) DeepCopy() *FabricQuotaStatus {
	if in == nil {
		return nil
	}
	out := new(FabricQuotaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUQuotaSpec) DeepCopyInto(out *GPUQuotaSpec) {
	*out = *in
	if in.AllowedGPUTypes != nil {
		in, out := &in.AllowedGPUTypes, &out.AllowedGPUTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUQuotaSpec.
func (in *GPUQuotaSpec) DeepCopy() *GPUQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(GPUQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaUsage) DeepCopyInto(out *QuotaUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaUsage.
func (in *QuotaUsage) DeepCopy() *QuotaUsage {
	if in == nil {
		return nil
	}
	out := new(QuotaUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricCostPredictor) DeepCopyInto(out *FabricCostPredictor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricCostPredictor.
func (in *FabricCostPredictor) DeepCopy() *FabricCostPredictor {
	if in == nil {
		return nil
	}
	out := new(FabricCostPredictor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricCostPredictor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricCostPredictorList) DeepCopyInto(out *FabricCostPredictorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricCostPredictor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricCostPredictorList.
func (in *FabricCostPredictorList) DeepCopy() *FabricCostPredictorList {
	if in == nil {
		return nil
	}
	out := new(FabricCostPredictorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricCostPredictorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricCostPredictorSpec) DeepCopyInto(out *FabricCostPredictorSpec) {
	*out = *in
	in.HistoricalData.DeepCopyInto(&out.HistoricalData)
	in.Models.DeepCopyInto(&out.Models)
	in.Alternatives.DeepCopyInto(&out.Alternatives)
	out.Integration = in.Integration
	in.Pricing.DeepCopyInto(&out.Pricing)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricCostPredictorSpec.
func (in *FabricCostPredictorSpec) DeepCopy() *FabricCostPredictorSpec {
	if in == nil {
		return nil
	}
	out := new(FabricCostPredictorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricCostPredictorStatus) DeepCopyInto(out *FabricCostPredictorStatus) {
	*out = *in
	out.PredictionAccuracy = in.PredictionAccuracy
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricCostPredictorStatus.
func (in *FabricCostPredictorStatus) DeepCopy() *FabricCostPredictorStatus {
	if in == nil {
		return nil
	}
	out := new(FabricCostPredictorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HistoricalDataSpec) DeepCopyInto(out *HistoricalDataSpec) {
	*out = *in
	if in.SimilarityFactors != nil {
		in, out := &in.SimilarityFactors, &out.SimilarityFactors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HistoricalDataSpec.
func (in *HistoricalDataSpec) DeepCopy() *HistoricalDataSpec {
	if in == nil {
		return nil
	}
	out := new(HistoricalDataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictionModelsSpec) DeepCopyInto(out *PredictionModelsSpec) {
	*out = *in
	in.TrainingTime.DeepCopyInto(&out.TrainingTime)
	out.CostEstimation = in.CostEstimation
	out.QueueTime = in.QueueTime
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictionModelsSpec.
func (in *PredictionModelsSpec) DeepCopy() *PredictionModelsSpec {
	if in == nil {
		return nil
	}
	out := new(PredictionModelsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingTimeModelSpec) DeepCopyInto(out *TrainingTimeModelSpec) {
	*out = *in
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingTimeModelSpec.
func (in *TrainingTimeModelSpec) DeepCopy() *TrainingTimeModelSpec {
	if in == nil {
		return nil
	}
	out := new(TrainingTimeModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostEstimationModelSpec) DeepCopyInto(out *CostEstimationModelSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostEstimationModelSpec.
func (in *CostEstimationModelSpec) DeepCopy() *CostEstimationModelSpec {
	if in == nil {
		return nil
	}
	out := new(CostEstimationModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueTimeModelSpec) DeepCopyInto(out *QueueTimeModelSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueTimeModelSpec.
func (in *QueueTimeModelSpec) DeepCopy() *QueueTimeModelSpec {
	if in == nil {
		return nil
	}
	out := new(QueueTimeModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlternativesSpec) DeepCopyInto(out *AlternativesSpec) {
	*out = *in
	if in.Strategies != nil {
		in, out := &in.Strategies, &out.Strategies
		*out = make([]AlternativeStrategy, len(*in))
		copy(*out, *in)
	}
	if in.GPUTypesToConsider != nil {
		in, out := &in.GPUTypesToConsider, &out.GPUTypesToConsider
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlternativesSpec.
func (in *AlternativesSpec) DeepCopy() *AlternativesSpec {
	if in == nil {
		return nil
	}
	out := new(AlternativesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlternativeStrategy) DeepCopyInto(out *AlternativeStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlternativeStrategy.
func (in *AlternativeStrategy) DeepCopy() *AlternativeStrategy {
	if in == nil {
		return nil
	}
	out := new(AlternativeStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationSpec) DeepCopyInto(out *IntegrationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationSpec.
func (in *IntegrationSpec) DeepCopy() *IntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(IntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PricingSpec) DeepCopyInto(out *PricingSpec) {
	*out = *in
	if in.PerGpuHour != nil {
		in, out := &in.PerGpuHour, &out.PerGpuHour
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PricingSpec.
func (in *PricingSpec) DeepCopy() *PricingSpec {
	if in == nil {
		return nil
	}
	out := new(PricingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictionAccuracyStatus) DeepCopyInto(out *PredictionAccuracyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictionAccuracyStatus.
func (in *PredictionAccuracyStatus) DeepCopy() *PredictionAccuracyStatus {
	if in == nil {
		return nil
	}
	out := new(PredictionAccuracyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccuracyMetrics) DeepCopyInto(out *AccuracyMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccuracyMetrics.
func (in *AccuracyMetrics) DeepCopy() *AccuracyMetrics {
	if in == nil {
		return nil
	}
	out := new(AccuracyMetrics)
	in.DeepCopyInto(out)
	return out
}
