//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccuracyMetrics) DeepCopyInto(out *AccuracyMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccuracyMetrics.
func (in *AccuracyMetrics) DeepCopy() *AccuracyMetrics {
	if in == nil {
		return nil
	}
	out := new(AccuracyMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlternativeStrategy) DeepCopyInto(out *AlternativeStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlternativeStrategy.
func (in *AlternativeStrategy) DeepCopy() *AlternativeStrategy {
	if in == nil {
		return nil
	}
	out := new(AlternativeStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlternativesSpec) DeepCopyInto(out *AlternativesSpec) {
	*out = *in
	if in.Strategies != nil {
		in, out := &in.Strategies, &out.Strategies
		*out = make([]AlternativeStrategy, len(*in))
		copy(*out, *in)
	}
	if in.GPUTypesToConsider != nil {
		in, out := &in.GPUTypesToConsider, &out.GPUTypesToConsider
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlternativesSpec.
func (in *AlternativesSpec) DeepCopy() *AlternativesSpec {
	if in == nil {
		return nil
	}
	out := new(AlternativesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnomalyRule) DeepCopyInto(out *AnomalyRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnomalyRule.
func (in *AnomalyRule) DeepCopy() *AnomalyRule {
	if in == nil {
		return nil
	}
	out := new(AnomalyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditAnomalyDetection) DeepCopyInto(out *AuditAnomalyDetection) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]AnomalyRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditAnomalyDetection.
func (in *AuditAnomalyDetection) DeepCopy() *AuditAnomalyDetection {
	if in == nil {
		return nil
	}
	out := new(AuditAnomalyDetection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditApprovalRequired) DeepCopyInto(out *AuditApprovalRequired) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditApprovalRequired.
func (in *AuditApprovalRequired) DeepCopy() *AuditApprovalRequired {
	if in == nil {
		return nil
	}
	out := new(AuditApprovalRequired)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditArchival) DeepCopyInto(out *AuditArchival) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditArchival.
func (in *AuditArchival) DeepCopy() *AuditArchival {
	if in == nil {
		return nil
	}
	out := new(AuditArchival)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditCompliance) DeepCopyInto(out *AuditCompliance) {
	*out = *in
	if in.Frameworks != nil {
		in, out := &in.Frameworks, &out.Frameworks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ApprovalRequired != nil {
		in, out := &in.ApprovalRequired, &out.ApprovalRequired
		*out = new(AuditApprovalRequired)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditCompliance.
func (in *AuditCompliance) DeepCopy() *AuditCompliance {
	if in == nil {
		return nil
	}
	out := new(AuditCompliance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditEntry) DeepCopyInto(out *AuditEntry) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditEntry.
func (in *AuditEntry) DeepCopy() *AuditEntry {
	if in == nil {
		return nil
	}
	out := new(AuditEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditEvents) DeepCopyInto(out *AuditEvents) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditEvents.
func (in *AuditEvents) DeepCopy() *AuditEvents {
	if in == nil {
		return nil
	}
	out := new(AuditEvents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditReportRef) DeepCopyInto(out *AuditReportRef) {
	*out = *in
	if in.GeneratedAt != nil {
		in, out := &in.GeneratedAt, &out.GeneratedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditReportRef.
func (in *AuditReportRef) DeepCopy() *AuditReportRef {
	if in == nil {
		return nil
	}
	out := new(AuditReportRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditReporting) DeepCopyInto(out *AuditReporting) {
	*out = *in
	if in.Recipients != nil {
		in, out := &in.Recipients, &out.Recipients
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditReporting.
func (in *AuditReporting) DeepCopy() *AuditReporting {
	if in == nil {
		return nil
	}
	out := new(AuditReporting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditRetention) DeepCopyInto(out *AuditRetention) {
	*out = *in
	if in.Archival != nil {
		in, out := &in.Archival, &out.Archival
		*out = new(AuditArchival)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditRetention.
func (in *AuditRetention) DeepCopy() *AuditRetention {
	if in == nil {
		return nil
	}
	out := new(AuditRetention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditScope) DeepCopyInto(out *AuditScope) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditScope.
func (in *AuditScope) DeepCopy() *AuditScope {
	if in == nil {
		return nil
	}
	out := new(AuditScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditViolation) DeepCopyInto(out *AuditViolation) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditViolation.
func (in *AuditViolation) DeepCopy() *AuditViolation {
	if in == nil {
		return nil
	}
	out := new(AuditViolation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingContact) DeepCopyInto(out *BillingContact) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingContact.
func (in *BillingContact) DeepCopy() *BillingContact {
	if in == nil {
		return nil
	}
	out := new(BillingContact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetAlert) DeepCopyInto(out *BudgetAlert) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Recipients != nil {
		in, out := &in.Recipients, &out.Recipients
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetAlert.
func (in *BudgetAlert) DeepCopy() *BudgetAlert {
	if in == nil {
		return nil
	}
	out := new(BudgetAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetAlertEvent) DeepCopyInto(out *BudgetAlertEvent) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetAlertEvent.
func (in *BudgetAlertEvent) DeepCopy() *BudgetAlertEvent {
	if in == nil {
		return nil
	}
	out := new(BudgetAlertEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetCurrentPeriod) DeepCopyInto(out *BudgetCurrentPeriod) {
	*out = *in
	in.StartDate.DeepCopyInto(&out.StartDate)
	in.EndDate.DeepCopyInto(&out.EndDate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetCurrentPeriod.
func (in *BudgetCurrentPeriod) DeepCopy() *BudgetCurrentPeriod {
	if in == nil {
		return nil
	}
	out := new(BudgetCurrentPeriod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetEnforcement) DeepCopyInto(out *BudgetEnforcement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetEnforcement.
func (in *BudgetEnforcement) DeepCopy() *BudgetEnforcement {
	if in == nil {
		return nil
	}
	out := new(BudgetEnforcement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetForecast) DeepCopyInto(out *BudgetForecast) {
	*out = *in
	if in.EstimatedExhaustionDate != nil {
		in, out := &in.EstimatedExhaustionDate, &out.EstimatedExhaustionDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetForecast.
func (in *BudgetForecast) DeepCopy() *BudgetForecast {
	if in == nil {
		return nil
	}
	out := new(BudgetForecast)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetLimits) DeepCopyInto(out *BudgetLimits) {
	*out = *in
	if in.GPUTypeHours != nil {
		in, out := &in.GPUTypeHours, &out.GPUTypeHours
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetLimits.
func (in *BudgetLimits) DeepCopy() *BudgetLimits {
	if in == nil {
		return nil
	}
	out := new(BudgetLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetPeriod) DeepCopyInto(out *BudgetPeriod) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetPeriod.
func (in *BudgetPeriod) DeepCopy() *BudgetPeriod {
	if in == nil {
		return nil
	}
	out := new(BudgetPeriod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetPriority) DeepCopyInto(out *BudgetPriority) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetPriority.
func (in *BudgetPriority) DeepCopy() *BudgetPriority {
	if in == nil {
		return nil
	}
	out := new(BudgetPriority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetRollover) DeepCopyInto(out *BudgetRollover) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetRollover.
func (in *BudgetRollover) DeepCopy() *BudgetRollover {
	if in == nil {
		return nil
	}
	out := new(BudgetRollover)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetScope) DeepCopyInto(out *BudgetScope) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetScope.
func (in *BudgetScope) DeepCopy() *BudgetScope {
	if in == nil {
		return nil
	}
	out := new(BudgetScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetSpec) DeepCopyInto(out *BudgetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetSpec.
func (in *BudgetSpec) DeepCopy() *BudgetSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetStatus) DeepCopyInto(out *BudgetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetStatus.
func (in *BudgetStatus) DeepCopy() *BudgetStatus {
	if in == nil {
		return nil
	}
	out := new(BudgetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetUsage) DeepCopyInto(out *BudgetUsage) {
	*out = *in
	if in.GPUTypeHours != nil {
		in, out := &in.GPUTypeHours, &out.GPUTypeHours
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetUsage.
func (in *BudgetUsage) DeepCopy() *BudgetUsage {
	if in == nil {
		return nil
	}
	out := new(BudgetUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetUtilization) DeepCopyInto(out *BudgetUtilization) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetUtilization.
func (in *BudgetUtilization) DeepCopy() *BudgetUtilization {
	if in == nil {
		return nil
	}
	out := new(BudgetUtilization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChargebackAllocationModel) DeepCopyInto(out *ChargebackAllocationModel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChargebackAllocationModel.
func (in *ChargebackAllocationModel) DeepCopy() *ChargebackAllocationModel {
	if in == nil {
		return nil
	}
	out := new(ChargebackAllocationModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChargebackCurrentPeriod) DeepCopyInto(out *ChargebackCurrentPeriod) {
	*out = *in
	if in.CostCenters != nil {
		in, out := &in.CostCenters, &out.CostCenters
		*out = make([]CostCenterStatus, len(*in))
		copy(*out, *in)
	}
	if in.ByResourceType != nil {
		in, out := &in.ByResourceType, &out.ByResourceType
		*out = new(ResourceTypeCosts)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChargebackCurrentPeriod.
func (in *ChargebackCurrentPeriod) DeepCopy() *ChargebackCurrentPeriod {
	if in == nil {
		return nil
	}
	out := new(ChargebackCurrentPeriod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChargebackPeriod) DeepCopyInto(out *ChargebackPeriod) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChargebackPeriod.
func (in *ChargebackPeriod) DeepCopy() *ChargebackPeriod {
	if in == nil {
		return nil
	}
	out := new(ChargebackPeriod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChargebackPricing) DeepCopyInto(out *ChargebackPricing) {
	*out = *in
	if in.GPURates != nil {
		in, out := &in.GPURates, &out.GPURates
		*out = make(map[string]GPURate, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StoragePricing)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkPricing)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChargebackPricing.
func (in *ChargebackPricing) DeepCopy() *ChargebackPricing {
	if in == nil {
		return nil
	}
	out := new(ChargebackPricing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChargebackReportRef) DeepCopyInto(out *ChargebackReportRef) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChargebackReportRef.
func (in *ChargebackReportRef) DeepCopy() *ChargebackReportRef {
	if in == nil {
		return nil
	}
	out := new(ChargebackReportRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChargebackReports) DeepCopyInto(out *ChargebackReports) {
	*out = *in
	if in.Formats != nil {
		in, out := &in.Formats, &out.Formats
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChargebackReports.
func (in *ChargebackReports) DeepCopy() *ChargebackReports {
	if in == nil {
		return nil
	}
	out := new(ChargebackReports)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostCenter) DeepCopyInto(out *CostCenter) {
	*out = *in
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Budget != nil {
		in, out := &in.Budget, &out.Budget
		*out = new(CostCenterBudget)
		**out = **in
	}
	if in.BillingContact != nil {
		in, out := &in.BillingContact, &out.BillingContact
		*out = new(BillingContact)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostCenter.
func (in *CostCenter) DeepCopy() *CostCenter {
	if in == nil {
		return nil
	}
	out := new(CostCenter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostCenterBudget) DeepCopyInto(out *CostCenterBudget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostCenterBudget.
func (in *CostCenterBudget) DeepCopy() *CostCenterBudget {
	if in == nil {
		return nil
	}
	out := new(CostCenterBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostCenterStatus) DeepCopyInto(out *CostCenterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostCenterStatus.
func (in *CostCenterStatus) DeepCopy() *CostCenterStatus {
	if in == nil {
		return nil
	}
	out := new(CostCenterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostEstimationModelSpec) DeepCopyInto(out *CostEstimationModelSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostEstimationModelSpec.
func (in *CostEstimationModelSpec) DeepCopy() *CostEstimationModelSpec {
	if in == nil {
		return nil
	}
	out := new(CostEstimationModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAIJob) DeepCopyInto(out *FabricAIJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAIJob.
func (in *FabricAIJob) DeepCopy() *FabricAIJob {
	if in == nil {
		return nil
	}
	out := new(FabricAIJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricAIJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAIJobDistributedSpec) DeepCopyInto(out *FabricAIJobDistributedSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAIJobDistributedSpec.
func (in *FabricAIJobDistributedSpec) DeepCopy() *FabricAIJobDistributedSpec {
	if in == nil {
		return nil
	}
	out := new(FabricAIJobDistributedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAIJobList) DeepCopyInto(out *FabricAIJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricAIJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAIJobList.
func (in *FabricAIJobList) DeepCopy() *FabricAIJobList {
	if in == nil {
		return nil
	}
	out := new(FabricAIJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricAIJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAIJobSpec) DeepCopyInto(out *FabricAIJobSpec) {
	*out = *in
	if in.Distributed != nil {
		in, out := &in.Distributed, &out.Distributed
		*out = new(FabricAIJobDistributedSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAIJobSpec.
func (in *FabricAIJobSpec) DeepCopy() *FabricAIJobSpec {
	if in == nil {
		return nil
	}
	out := new(FabricAIJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAIJobStatus) DeepCopyInto(out *FabricAIJobStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodesAllocated != nil {
		in, out := &in.NodesAllocated, &out.NodesAllocated
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAIJobStatus.
func (in *FabricAIJobStatus) DeepCopy() *FabricAIJobStatus {
	if in == nil {
		return nil
	}
	out := new(FabricAIJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAudit) DeepCopyInto(out *FabricAudit) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAudit.
func (in *FabricAudit) DeepCopy() *FabricAudit {
	if in == nil {
		return nil
	}
	out := new(FabricAudit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricAudit) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAuditList) DeepCopyInto(out *FabricAuditList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricAudit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAuditList.
func (in *FabricAuditList) DeepCopy() *FabricAuditList {
	if in == nil {
		return nil
	}
	out := new(FabricAuditList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricAuditList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAuditSpec) DeepCopyInto(out *FabricAuditSpec) {
	*out = *in
	out.Scope = in.Scope
	in.Retention.DeepCopyInto(&out.Retention)
	out.Events = in.Events
	in.Compliance.DeepCopyInto(&out.Compliance)
	in.Reporting.DeepCopyInto(&out.Reporting)
	if in.AnomalyDetection != nil {
		in, out := &in.AnomalyDetection, &out.AnomalyDetection
		*out = new(AuditAnomalyDetection)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAuditSpec.
func (in *FabricAuditSpec) DeepCopy() *FabricAuditSpec {
	if in == nil {
		return nil
	}
	out := new(FabricAuditSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricAuditStatus) DeepCopyInto(out *FabricAuditStatus) {
	*out = *in
	if in.LastAuditTime != nil {
		in, out := &in.LastAuditTime, &out.LastAuditTime
		*out = (*in).DeepCopy()
	}
	if in.Violations != nil {
		in, out := &in.Violations, &out.Violations
		*out = make([]AuditViolation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReport != nil {
		in, out := &in.LastReport, &out.LastReport
		*out = new(AuditReportRef)
		(*in).DeepCopyInto(*out)
	}
	if in.AuditEntries != nil {
		in, out := &in.AuditEntries, &out.AuditEntries
		*out = make([]AuditEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricAuditStatus.
func (in *FabricAuditStatus) DeepCopy() *FabricAuditStatus {
	if in == nil {
		return nil
	}
	out := new(FabricAuditStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricBudget) DeepCopyInto(out *FabricBudget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricBudget.
func (in *FabricBudget) DeepCopy() *FabricBudget {
	if in == nil {
		return nil
	}
	out := new(FabricBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricBudget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricBudgetList) DeepCopyInto(out *FabricBudgetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricBudget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricBudgetList.
func (in *FabricBudgetList) DeepCopy() *FabricBudgetList {
	if in == nil {
		return nil
	}
	out := new(FabricBudgetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricBudgetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricBudgetSpec) DeepCopyInto(out *FabricBudgetSpec) {
	*out = *in
	out.Scope = in.Scope
	out.Period = in.Period
	in.Limits.DeepCopyInto(&out.Limits)
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = make([]BudgetAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Enforcement != nil {
		in, out := &in.Enforcement, &out.Enforcement
		*out = new(BudgetEnforcement)
		**out = **in
	}
	if in.Rollover != nil {
		in, out := &in.Rollover, &out.Rollover
		*out = new(BudgetRollover)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(BudgetPriority)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricBudgetSpec.
func (in *FabricBudgetSpec) DeepCopy() *FabricBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(FabricBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricBudgetStatus) DeepCopyInto(out *FabricBudgetStatus) {
	*out = *in
	if in.CurrentPeriod != nil {
		in, out := &in.CurrentPeriod, &out.CurrentPeriod
		*out = new(BudgetCurrentPeriod)
		(*in).DeepCopyInto(*out)
	}
	if in.Usage != nil {
		in, out := &in.Usage, &out.Usage
		*out = new(BudgetUsage)
		(*in).DeepCopyInto(*out)
	}
	if in.Utilization != nil {
		in, out := &in.Utilization, &out.Utilization
		*out = new(BudgetUtilization)
		**out = **in
	}
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = make([]BudgetAlertEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Forecast != nil {
		in, out := &in.Forecast, &out.Forecast
		*out = new(BudgetForecast)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricBudgetStatus.
func (in *FabricBudgetStatus) DeepCopy() *FabricBudgetStatus {
	if in == nil {
		return nil
	}
	out := new(FabricBudgetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricChargeback) DeepCopyInto(out *FabricChargeback) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricChargeback.
func (in *FabricChargeback) DeepCopy() *FabricChargeback {
	if in == nil {
		return nil
	}
	out := new(FabricChargeback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricChargeback) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricChargebackList) DeepCopyInto(out *FabricChargebackList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricChargeback, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricChargebackList.
func (in *FabricChargebackList) DeepCopy() *FabricChargebackList {
	if in == nil {
		return nil
	}
	out := new(FabricChargebackList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricChargebackList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricChargebackSpec) DeepCopyInto(out *FabricChargebackSpec) {
	*out = *in
	out.Period = in.Period
	out.AllocationModel = in.AllocationModel
	in.Pricing.DeepCopyInto(&out.Pricing)
	if in.CostCenters != nil {
		in, out := &in.CostCenters, &out.CostCenters
		*out = make([]CostCenter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Reports != nil {
		in, out := &in.Reports, &out.Reports
		*out = new(ChargebackReports)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricChargebackSpec.
func (in *FabricChargebackSpec) DeepCopy() *FabricChargebackSpec {
	if in == nil {
		return nil
	}
	out := new(FabricChargebackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricChargebackStatus) DeepCopyInto(out *FabricChargebackStatus) {
	*out = *in
	if in.CurrentPeriod != nil {
		in, out := &in.CurrentPeriod, &out.CurrentPeriod
		*out = new(ChargebackCurrentPeriod)
		(*in).DeepCopyInto(*out)
	}
	if in.LastReport != nil {
		in, out := &in.LastReport, &out.LastReport
		*out = new(ChargebackReportRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricChargebackStatus.
func (in *FabricChargebackStatus) DeepCopy() *FabricChargebackStatus {
	if in == nil {
		return nil
	}
	out := new(FabricChargebackStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricCostPredictor) DeepCopyInto(out *FabricCostPredictor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricCostPredictor.
func (in *FabricCostPredictor) DeepCopy() *FabricCostPredictor {
	if in == nil {
		return nil
	}
	out := new(FabricCostPredictor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricCostPredictor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricCostPredictorList) DeepCopyInto(out *FabricCostPredictorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricCostPredictor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricCostPredictorList.
func (in *FabricCostPredictorList) DeepCopy() *FabricCostPredictorList {
	if in == nil {
		return nil
	}
	out := new(FabricCostPredictorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricCostPredictorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricCostPredictorSpec) DeepCopyInto(out *FabricCostPredictorSpec) {
	*out = *in
	in.HistoricalData.DeepCopyInto(&out.HistoricalData)
	in.Models.DeepCopyInto(&out.Models)
	in.Alternatives.DeepCopyInto(&out.Alternatives)
	out.Integration = in.Integration
	in.Pricing.DeepCopyInto(&out.Pricing)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricCostPredictorSpec.
func (in *FabricCostPredictorSpec) DeepCopy() *FabricCostPredictorSpec {
	if in == nil {
		return nil
	}
	out := new(FabricCostPredictorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricCostPredictorStatus) DeepCopyInto(out *FabricCostPredictorStatus) {
	*out = *in
	out.PredictionAccuracy = in.PredictionAccuracy
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricCostPredictorStatus.
func (in *FabricCostPredictorStatus) DeepCopy() *FabricCostPredictorStatus {
	if in == nil {
		return nil
	}
	out := new(FabricCostPredictorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricQuota) DeepCopyInto(out *FabricQuota) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricQuota.
func (in *FabricQuota) DeepCopy() *FabricQuota {
	if in == nil {
		return nil
	}
	out := new(FabricQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricQuota) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricQuotaList) DeepCopyInto(out *FabricQuotaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricQuota, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricQuotaList.
func (in *FabricQuotaList) DeepCopy() *FabricQuotaList {
	if in == nil {
		return nil
	}
	out := new(FabricQuotaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricQuotaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricQuotaPolicy) DeepCopyInto(out *FabricQuotaPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricQuotaPolicy.
func (in *FabricQuotaPolicy) DeepCopy() *FabricQuotaPolicy {
	if in == nil {
		return nil
	}
	out := new(FabricQuotaPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricQuotaPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricQuotaPolicyList) DeepCopyInto(out *FabricQuotaPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricQuotaPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricQuotaPolicyList.
func (in *FabricQuotaPolicyList) DeepCopy() *FabricQuotaPolicyList {
	if in == nil {
		return nil
	}
	out := new(FabricQuotaPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricQuotaPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricQuotaPolicySpec) DeepCopyInto(out *FabricQuotaPolicySpec) {
	*out = *in
	out.Scope = in.Scope
	if in.Hierarchy != nil {
		in, out := &in.Hierarchy, &out.Hierarchy
		*out = new(QuotaPolicyHierarchy)
		**out = **in
	}
	in.Limits.DeepCopyInto(&out.Limits)
	if in.Allocation != nil {
		in, out := &in.Allocation, &out.Allocation
		*out = new(QuotaPolicyAllocation)
		(*in).DeepCopyInto(*out)
	}
	if in.Enforcement != nil {
		in, out := &in.Enforcement, &out.Enforcement
		*out = new(QuotaPolicyEnforcement)
		**out = **in
	}
	if in.TimeBased != nil {
		in, out := &in.TimeBased, &out.TimeBased
		*out = new(QuotaPolicyTimeBased)
		(*in).DeepCopyInto(*out)
	}
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = new(QuotaPolicyAlerts)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricQuotaPolicySpec.
func (in *FabricQuotaPolicySpec) DeepCopy() *FabricQuotaPolicySpec {
	if in == nil {
		return nil
	}
	out := new(FabricQuotaPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricQuotaPolicyStatus) DeepCopyInto(out *FabricQuotaPolicyStatus) {
	*out = *in
	if in.Usage != nil {
		in, out := &in.Usage, &out.Usage
		*out = new(QuotaPolicyUsage)
		(*in).DeepCopyInto(*out)
	}
	if in.Utilization != nil {
		in, out := &in.Utilization, &out.Utilization
		*out = new(QuotaPolicyUtilization)
		**out = **in
	}
	if in.Children != nil {
		in, out := &in.Children, &out.Children
		*out = make([]QuotaPolicyChildStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricQuotaPolicyStatus.
func (in *FabricQuotaPolicyStatus) DeepCopy() *FabricQuotaPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(FabricQuotaPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricQuotaSpec) DeepCopyInto(out *FabricQuotaSpec) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.GPUQuota.DeepCopyInto(&out.GPUQuota)
	if in.Budget != nil {
		in, out := &in.Budget, &out.Budget
		*out = new(BudgetSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricQuotaSpec.
func (in *FabricQuotaSpec) DeepCopy() *FabricQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(FabricQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricQuotaStatus) DeepCopyInto(out *FabricQuotaStatus) {
	*out = *in
	out.CurrentUsage = in.CurrentUsage
	if in.BudgetStatus != nil {
		in, out := &in.BudgetStatus, &out.BudgetStatus
		*out = new(BudgetStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricQuotaStatus.
func (in *FabricQuotaStatus) DeepCopy() *FabricQuotaStatus {
	if in == nil {
		return nil
	}
	out := new(FabricQuotaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricReservation) DeepCopyInto(out *FabricReservation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricReservation.
func (in *FabricReservation) DeepCopy() *FabricReservation {
	if in == nil {
		return nil
	}
	out := new(FabricReservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricReservation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricReservationList) DeepCopyInto(out *FabricReservationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricReservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricReservationList.
func (in *FabricReservationList) DeepCopy() *FabricReservationList {
	if in == nil {
		return nil
	}
	out := new(FabricReservationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricReservationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricReservationSpec) DeepCopyInto(out *FabricReservationSpec) {
	*out = *in
	out.Owner = in.Owner
	in.Resources.DeepCopyInto(&out.Resources)
	in.Schedule.DeepCopyInto(&out.Schedule)
	if in.Guarantees != nil {
		in, out := &in.Guarantees, &out.Guarantees
		*out = new(ReservationGuarantees)
		(*in).DeepCopyInto(*out)
	}
	if in.Billing != nil {
		in, out := &in.Billing, &out.Billing
		*out = new(ReservationBilling)
		**out = **in
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = new(ReservationNotifications)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricReservationSpec.
func (in *FabricReservationSpec) DeepCopy() *FabricReservationSpec {
	if in == nil {
		return nil
	}
	out := new(FabricReservationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricReservationStatus) DeepCopyInto(out *FabricReservationStatus) {
	*out = *in
	if in.ActualStartTime != nil {
		in, out := &in.ActualStartTime, &out.ActualStartTime
		*out = (*in).DeepCopy()
	}
	if in.ActualEndTime != nil {
		in, out := &in.ActualEndTime, &out.ActualEndTime
		*out = (*in).DeepCopy()
	}
	if in.AllocatedNodes != nil {
		in, out := &in.AllocatedNodes, &out.AllocatedNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UtilizationMetrics != nil {
		in, out := &in.UtilizationMetrics, &out.UtilizationMetrics
		*out = new(ReservationUtilization)
		**out = **in
	}
	if in.Cost != nil {
		in, out := &in.Cost, &out.Cost
		*out = new(ReservationCost)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricReservationStatus.
func (in *FabricReservationStatus) DeepCopy() *FabricReservationStatus {
	if in == nil {
		return nil
	}
	out := new(FabricReservationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricSLA) DeepCopyInto(out *FabricSLA) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricSLA.
func (in *FabricSLA) DeepCopy() *FabricSLA {
	if in == nil {
		return nil
	}
	out := new(FabricSLA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricSLA) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricSLAList) DeepCopyInto(out *FabricSLAList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricSLA, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricSLAList.
func (in *FabricSLAList) DeepCopy() *FabricSLAList {
	if in == nil {
		return nil
	}
	out := new(FabricSLAList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricSLAList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricSLASpec) DeepCopyInto(out *FabricSLASpec) {
	*out = *in
	out.Scope = in.Scope
	if in.Performance != nil {
		in, out := &in.Performance, &out.Performance
		*out = new(SLAPerformance)
		(*in).DeepCopyInto(*out)
	}
	if in.Availability != nil {
		in, out := &in.Availability, &out.Availability
		*out = new(SLAAvailability)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(SLAResources)
		(*in).DeepCopyInto(*out)
	}
	if in.FailureHandling != nil {
		in, out := &in.FailureHandling, &out.FailureHandling
		*out = new(SLAFailureHandling)
		(*in).DeepCopyInto(*out)
	}
	if in.Support != nil {
		in, out := &in.Support, &out.Support
		*out = new(SLASupport)
		(*in).DeepCopyInto(*out)
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(SLAMonitoring)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricSLASpec.
func (in *FabricSLASpec) DeepCopy() *FabricSLASpec {
	if in == nil {
		return nil
	}
	out := new(FabricSLASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricSLAStatus) DeepCopyInto(out *FabricSLAStatus) {
	*out = *in
	if in.Compliance != nil {
		in, out := &in.Compliance, &out.Compliance
		*out = new(SLAComplianceStatus)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(SLAMetricsStatus)
		**out = **in
	}
	if in.Breaches != nil {
		in, out := &in.Breaches, &out.Breaches
		*out = make([]SLABreach, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricSLAStatus.
func (in *FabricSLAStatus) DeepCopy() *FabricSLAStatus {
	if in == nil {
		return nil
	}
	out := new(FabricSLAStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTenant) DeepCopyInto(out *FabricTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTenant.
func (in *FabricTenant) DeepCopy() *FabricTenant {
	if in == nil {
		return nil
	}
	out := new(FabricTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTenantList) DeepCopyInto(out *FabricTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTenantList.
func (in *FabricTenantList) DeepCopy() *FabricTenantList {
	if in == nil {
		return nil
	}
	out := new(FabricTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTenantSpec) DeepCopyInto(out *FabricTenantSpec) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]TenantMember, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Quotas != nil {
		in, out := &in.Quotas, &out.Quotas
		*out = new(TenantQuotas)
		(*in).DeepCopyInto(*out)
	}
	if in.Priorities != nil {
		in, out := &in.Priorities, &out.Priorities
		*out = new(TenantPriorities)
		**out = **in
	}
	if in.NetworkPolicy != nil {
		in, out := &in.NetworkPolicy, &out.NetworkPolicy
		*out = new(TenantNetworkPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.StorageQuotas != nil {
		in, out := &in.StorageQuotas, &out.StorageQuotas
		*out = new(TenantStorageQuotas)
		**out = **in
	}
	if in.JobDefaults != nil {
		in, out := &in.JobDefaults, &out.JobDefaults
		*out = new(TenantJobDefaults)
		**out = **in
	}
	if in.Billing != nil {
		in, out := &in.Billing, &out.Billing
		*out = new(TenantBilling)
		**out = **in
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = new(TenantNotifications)
		(*in).DeepCopyInto(*out)
	}
	if in.Governance != nil {
		in, out := &in.Governance, &out.Governance
		*out = new(TenantGovernance)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTenantSpec.
func (in *FabricTenantSpec) DeepCopy() *FabricTenantSpec {
	if in == nil {
		return nil
	}
	out := new(FabricTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricTenantStatus) DeepCopyInto(out *FabricTenantStatus) {
	*out = *in
	if in.CurrentUsage != nil {
		in, out := &in.CurrentUsage, &out.CurrentUsage
		*out = new(TenantCurrentUsage)
		**out = **in
	}
	if in.QuotaUtilization != nil {
		in, out := &in.QuotaUtilization, &out.QuotaUtilization
		*out = new(TenantQuotaUtilization)
		**out = **in
	}
	if in.NamespacesManaged != nil {
		in, out := &in.NamespacesManaged, &out.NamespacesManaged
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricTenantStatus.
func (in *FabricTenantStatus) DeepCopy() *FabricTenantStatus {
	if in == nil {
		return nil
	}
	out := new(FabricTenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUQuotaSpec) DeepCopyInto(out *GPUQuotaSpec) {
	*out = *in
	if in.AllowedGPUTypes != nil {
		in, out := &in.AllowedGPUTypes, &out.AllowedGPUTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUQuotaSpec.
func (in *GPUQuotaSpec) DeepCopy() *GPUQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(GPUQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURate) DeepCopyInto(out *GPURate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURate.
func (in *GPURate) DeepCopy() *GPURate {
	if in == nil {
		return nil
	}
	out := new(GPURate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUTypeLimits) DeepCopyInto(out *GPUTypeLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUTypeLimits.
func (in *GPUTypeLimits) DeepCopy() *GPUTypeLimits {
	if in == nil {
		return nil
	}
	out := new(GPUTypeLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HistoricalDataSpec) DeepCopyInto(out *HistoricalDataSpec) {
	*out = *in
	if in.SimilarityFactors != nil {
		in, out := &in.SimilarityFactors, &out.SimilarityFactors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HistoricalDataSpec.
func (in *HistoricalDataSpec) DeepCopy() *HistoricalDataSpec {
	if in == nil {
		return nil
	}
	out := new(HistoricalDataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationSpec) DeepCopyInto(out *IntegrationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationSpec.
func (in *IntegrationSpec) DeepCopy() *IntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(IntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPricing) DeepCopyInto(out *NetworkPricing) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPricing.
func (in *NetworkPricing) DeepCopy() *NetworkPricing {
	if in == nil {
		return nil
	}
	out := new(NetworkPricing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictionAccuracyStatus) DeepCopyInto(out *PredictionAccuracyStatus) {
	*out = *in
	out.TimeEstimate = in.TimeEstimate
	out.CostEstimate = in.CostEstimate
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictionAccuracyStatus.
func (in *PredictionAccuracyStatus) DeepCopy() *PredictionAccuracyStatus {
	if in == nil {
		return nil
	}
	out := new(PredictionAccuracyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictionModelsSpec) DeepCopyInto(out *PredictionModelsSpec) {
	*out = *in
	in.TrainingTime.DeepCopyInto(&out.TrainingTime)
	out.CostEstimation = in.CostEstimation
	out.QueueTime = in.QueueTime
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictionModelsSpec.
func (in *PredictionModelsSpec) DeepCopy() *PredictionModelsSpec {
	if in == nil {
		return nil
	}
	out := new(PredictionModelsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PricingSpec) DeepCopyInto(out *PricingSpec) {
	*out = *in
	if in.PerGpuHour != nil {
		in, out := &in.PerGpuHour, &out.PerGpuHour
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PricingSpec.
func (in *PricingSpec) DeepCopy() *PricingSpec {
	if in == nil {
		return nil
	}
	out := new(PricingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueTimeModelSpec) DeepCopyInto(out *QueueTimeModelSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueTimeModelSpec.
func (in *QueueTimeModelSpec) DeepCopy() *QueueTimeModelSpec {
	if in == nil {
		return nil
	}
	out := new(QueueTimeModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicyAlerts) DeepCopyInto(out *QuotaPolicyAlerts) {
	*out = *in
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Recipients != nil {
		in, out := &in.Recipients, &out.Recipients
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicyAlerts.
func (in *QuotaPolicyAlerts) DeepCopy() *QuotaPolicyAlerts {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicyAlerts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicyAllocation) DeepCopyInto(out *QuotaPolicyAllocation) {
	*out = *in
	if in.Weights != nil {
		in, out := &in.Weights, &out.Weights
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicyAllocation.
func (in *QuotaPolicyAllocation) DeepCopy() *QuotaPolicyAllocation {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicyAllocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicyChildStatus) DeepCopyInto(out *QuotaPolicyChildStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicyChildStatus.
func (in *QuotaPolicyChildStatus) DeepCopy() *QuotaPolicyChildStatus {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicyChildStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicyCostLimits) DeepCopyInto(out *QuotaPolicyCostLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicyCostLimits.
func (in *QuotaPolicyCostLimits) DeepCopy() *QuotaPolicyCostLimits {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicyCostLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicyCostUsage) DeepCopyInto(out *QuotaPolicyCostUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicyCostUsage.
func (in *QuotaPolicyCostUsage) DeepCopy() *QuotaPolicyCostUsage {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicyCostUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicyEnforcement) DeepCopyInto(out *QuotaPolicyEnforcement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicyEnforcement.
func (in *QuotaPolicyEnforcement) DeepCopy() *QuotaPolicyEnforcement {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicyEnforcement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicyGPULimits) DeepCopyInto(out *QuotaPolicyGPULimits) {
	*out = *in
	if in.ByType != nil {
		in, out := &in.ByType, &out.ByType
		*out = make(map[string]GPUTypeLimits, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicyGPULimits.
func (in *QuotaPolicyGPULimits) DeepCopy() *QuotaPolicyGPULimits {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicyGPULimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicyGPUUsage) DeepCopyInto(out *QuotaPolicyGPUUsage) {
	*out = *in
	if in.ByType != nil {
		in, out := &in.ByType, &out.ByType
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicyGPUUsage.
func (in *QuotaPolicyGPUUsage) DeepCopy() *QuotaPolicyGPUUsage {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicyGPUUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicyHierarchy) DeepCopyInto(out *QuotaPolicyHierarchy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicyHierarchy.
func (in *QuotaPolicyHierarchy) DeepCopy() *QuotaPolicyHierarchy {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicyHierarchy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicyJobLimits) DeepCopyInto(out *QuotaPolicyJobLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicyJobLimits.
func (in *QuotaPolicyJobLimits) DeepCopy() *QuotaPolicyJobLimits {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicyJobLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicyJobUsage) DeepCopyInto(out *QuotaPolicyJobUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicyJobUsage.
func (in *QuotaPolicyJobUsage) DeepCopy() *QuotaPolicyJobUsage {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicyJobUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicyLimits) DeepCopyInto(out *QuotaPolicyLimits) {
	*out = *in
	if in.GPU != nil {
		in, out := &in.GPU, &out.GPU
		*out = new(QuotaPolicyGPULimits)
		(*in).DeepCopyInto(*out)
	}
	if in.Cost != nil {
		in, out := &in.Cost, &out.Cost
		*out = new(QuotaPolicyCostLimits)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(QuotaPolicyStorageLimits)
		(*in).DeepCopyInto(*out)
	}
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = new(QuotaPolicyJobLimits)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicyLimits.
func (in *QuotaPolicyLimits) DeepCopy() *QuotaPolicyLimits {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicyLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicySchedule) DeepCopyInto(out *QuotaPolicySchedule) {
	*out = *in
	if in.Window != nil {
		in, out := &in.Window, &out.Window
		*out = new(QuotaPolicyTimeWindow)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicySchedule.
func (in *QuotaPolicySchedule) DeepCopy() *QuotaPolicySchedule {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicySchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicyScope) DeepCopyInto(out *QuotaPolicyScope) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicyScope.
func (in *QuotaPolicyScope) DeepCopy() *QuotaPolicyScope {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicyScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicyStorageLimits) DeepCopyInto(out *QuotaPolicyStorageLimits) {
	*out = *in
	if in.ByClass != nil {
		in, out := &in.ByClass, &out.ByClass
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicyStorageLimits.
func (in *QuotaPolicyStorageLimits) DeepCopy() *QuotaPolicyStorageLimits {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicyStorageLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicyTimeBased) DeepCopyInto(out *QuotaPolicyTimeBased) {
	*out = *in
	if in.Schedules != nil {
		in, out := &in.Schedules, &out.Schedules
		*out = make([]QuotaPolicySchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicyTimeBased.
func (in *QuotaPolicyTimeBased) DeepCopy() *QuotaPolicyTimeBased {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicyTimeBased)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicyTimeWindow) DeepCopyInto(out *QuotaPolicyTimeWindow) {
	*out = *in
	if in.DaysOfWeek != nil {
		in, out := &in.DaysOfWeek, &out.DaysOfWeek
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicyTimeWindow.
func (in *QuotaPolicyTimeWindow) DeepCopy() *QuotaPolicyTimeWindow {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicyTimeWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicyUsage) DeepCopyInto(out *QuotaPolicyUsage) {
	*out = *in
	if in.GPU != nil {
		in, out := &in.GPU, &out.GPU
		*out = new(QuotaPolicyGPUUsage)
		(*in).DeepCopyInto(*out)
	}
	if in.Cost != nil {
		in, out := &in.Cost, &out.Cost
		*out = new(QuotaPolicyCostUsage)
		**out = **in
	}
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = new(QuotaPolicyJobUsage)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicyUsage.
func (in *QuotaPolicyUsage) DeepCopy() *QuotaPolicyUsage {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicyUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicyUtilization) DeepCopyInto(out *QuotaPolicyUtilization) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicyUtilization.
func (in *QuotaPolicyUtilization) DeepCopy() *QuotaPolicyUtilization {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicyUtilization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaUsage) DeepCopyInto(out *QuotaUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaUsage.
func (in *QuotaUsage) DeepCopy() *QuotaUsage {
	if in == nil {
		return nil
	}
	out := new(QuotaUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationBilling) DeepCopyInto(out *ReservationBilling) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationBilling.
func (in *ReservationBilling) DeepCopy() *ReservationBilling {
	if in == nil {
		return nil
	}
	out := new(ReservationBilling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationCost) DeepCopyInto(out *ReservationCost) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationCost.
func (in *ReservationCost) DeepCopy() *ReservationCost {
	if in == nil {
		return nil
	}
	out := new(ReservationCost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationGuarantees) DeepCopyInto(out *ReservationGuarantees) {
	*out = *in
	if in.SLA != nil {
		in, out := &in.SLA, &out.SLA
		*out = new(ReservationSLA)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationGuarantees.
func (in *ReservationGuarantees) DeepCopy() *ReservationGuarantees {
	if in == nil {
		return nil
	}
	out := new(ReservationGuarantees)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationNotifications) DeepCopyInto(out *ReservationNotifications) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationNotifications.
func (in *ReservationNotifications) DeepCopy() *ReservationNotifications {
	if in == nil {
		return nil
	}
	out := new(ReservationNotifications)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationOwner) DeepCopyInto(out *ReservationOwner) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationOwner.
func (in *ReservationOwner) DeepCopy() *ReservationOwner {
	if in == nil {
		return nil
	}
	out := new(ReservationOwner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationRecurrence) DeepCopyInto(out *ReservationRecurrence) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationRecurrence.
func (in *ReservationRecurrence) DeepCopy() *ReservationRecurrence {
	if in == nil {
		return nil
	}
	out := new(ReservationRecurrence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationResources) DeepCopyInto(out *ReservationResources) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationResources.
func (in *ReservationResources) DeepCopy() *ReservationResources {
	if in == nil {
		return nil
	}
	out := new(ReservationResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationSLA) DeepCopyInto(out *ReservationSLA) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationSLA.
func (in *ReservationSLA) DeepCopy() *ReservationSLA {
	if in == nil {
		return nil
	}
	out := new(ReservationSLA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationSchedule) DeepCopyInto(out *ReservationSchedule) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.Recurrence != nil {
		in, out := &in.Recurrence, &out.Recurrence
		*out = new(ReservationRecurrence)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationSchedule.
func (in *ReservationSchedule) DeepCopy() *ReservationSchedule {
	if in == nil {
		return nil
	}
	out := new(ReservationSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationUtilization) DeepCopyInto(out *ReservationUtilization) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationUtilization.
func (in *ReservationUtilization) DeepCopy() *ReservationUtilization {
	if in == nil {
		return nil
	}
	out := new(ReservationUtilization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceTypeCosts) DeepCopyInto(out *ResourceTypeCosts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceTypeCosts.
func (in *ResourceTypeCosts) DeepCopy() *ResourceTypeCosts {
	if in == nil {
		return nil
	}
	out := new(ResourceTypeCosts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLAAvailability) DeepCopyInto(out *SLAAvailability) {
	*out = *in
	if in.MaintenanceWindows != nil {
		in, out := &in.MaintenanceWindows, &out.MaintenanceWindows
		*out = make([]SLAMaintenanceWindow, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLAAvailability.
func (in *SLAAvailability) DeepCopy() *SLAAvailability {
	if in == nil {
		return nil
	}
	out := new(SLAAvailability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLABreach) DeepCopyInto(out *SLABreach) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLABreach.
func (in *SLABreach) DeepCopy() *SLABreach {
	if in == nil {
		return nil
	}
	out := new(SLABreach)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLACompensation) DeepCopyInto(out *SLACompensation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLACompensation.
func (in *SLACompensation) DeepCopy() *SLACompensation {
	if in == nil {
		return nil
	}
	out := new(SLACompensation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLAComplianceStatus) DeepCopyInto(out *SLAComplianceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLAComplianceStatus.
func (in *SLAComplianceStatus) DeepCopy() *SLAComplianceStatus {
	if in == nil {
		return nil
	}
	out := new(SLAComplianceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLAFailureHandling) DeepCopyInto(out *SLAFailureHandling) {
	*out = *in
	if in.Compensation != nil {
		in, out := &in.Compensation, &out.Compensation
		*out = new(SLACompensation)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLAFailureHandling.
func (in *SLAFailureHandling) DeepCopy() *SLAFailureHandling {
	if in == nil {
		return nil
	}
	out := new(SLAFailureHandling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLAMaintenanceWindow) DeepCopyInto(out *SLAMaintenanceWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLAMaintenanceWindow.
func (in *SLAMaintenanceWindow) DeepCopy() *SLAMaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(SLAMaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLAMetricsStatus) DeepCopyInto(out *SLAMetricsStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLAMetricsStatus.
func (in *SLAMetricsStatus) DeepCopy() *SLAMetricsStatus {
	if in == nil {
		return nil
	}
	out := new(SLAMetricsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLAMonitoring) DeepCopyInto(out *SLAMonitoring) {
	*out = *in
	if in.Reports != nil {
		in, out := &in.Reports, &out.Reports
		*out = new(SLAReports)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLAMonitoring.
func (in *SLAMonitoring) DeepCopy() *SLAMonitoring {
	if in == nil {
		return nil
	}
	out := new(SLAMonitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLAPerformance) DeepCopyInto(out *SLAPerformance) {
	*out = *in
	if in.MinThroughput != nil {
		in, out := &in.MinThroughput, &out.MinThroughput
		*out = new(SLAThroughput)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLAPerformance.
func (in *SLAPerformance) DeepCopy() *SLAPerformance {
	if in == nil {
		return nil
	}
	out := new(SLAPerformance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLAReports) DeepCopyInto(out *SLAReports) {
	*out = *in
	if in.Recipients != nil {
		in, out := &in.Recipients, &out.Recipients
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLAReports.
func (in *SLAReports) DeepCopy() *SLAReports {
	if in == nil {
		return nil
	}
	out := new(SLAReports)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLAReservedCapacity) DeepCopyInto(out *SLAReservedCapacity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLAReservedCapacity.
func (in *SLAReservedCapacity) DeepCopy() *SLAReservedCapacity {
	if in == nil {
		return nil
	}
	out := new(SLAReservedCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLAResources) DeepCopyInto(out *SLAResources) {
	*out = *in
	if in.GuaranteedGPUTypes != nil {
		in, out := &in.GuaranteedGPUTypes, &out.GuaranteedGPUTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReservedCapacity != nil {
		in, out := &in.ReservedCapacity, &out.ReservedCapacity
		*out = new(SLAReservedCapacity)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLAResources.
func (in *SLAResources) DeepCopy() *SLAResources {
	if in == nil {
		return nil
	}
	out := new(SLAResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLAScope) DeepCopyInto(out *SLAScope) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLAScope.
func (in *SLAScope) DeepCopy() *SLAScope {
	if in == nil {
		return nil
	}
	out := new(SLAScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLASupport) DeepCopyInto(out *SLASupport) {
	*out = *in
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLASupport.
func (in *SLASupport) DeepCopy() *SLASupport {
	if in == nil {
		return nil
	}
	out := new(SLASupport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLAThroughput) DeepCopyInto(out *SLAThroughput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLAThroughput.
func (in *SLAThroughput) DeepCopy() *SLAThroughput {
	if in == nil {
		return nil
	}
	out := new(SLAThroughput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePricing) DeepCopyInto(out *StoragePricing) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePricing.
func (in *StoragePricing) DeepCopy() *StoragePricing {
	if in == nil {
		return nil
	}
	out := new(StoragePricing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantBilling) DeepCopyInto(out *TenantBilling) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantBilling.
func (in *TenantBilling) DeepCopy() *TenantBilling {
	if in == nil {
		return nil
	}
	out := new(TenantBilling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantCostQuota) DeepCopyInto(out *TenantCostQuota) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantCostQuota.
func (in *TenantCostQuota) DeepCopy() *TenantCostQuota {
	if in == nil {
		return nil
	}
	out := new(TenantCostQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantCurrentUsage) DeepCopyInto(out *TenantCurrentUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantCurrentUsage.
func (in *TenantCurrentUsage) DeepCopy() *TenantCurrentUsage {
	if in == nil {
		return nil
	}
	out := new(TenantCurrentUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantGPUHoursQuota) DeepCopyInto(out *TenantGPUHoursQuota) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantGPUHoursQuota.
func (in *TenantGPUHoursQuota) DeepCopy() *TenantGPUHoursQuota {
	if in == nil {
		return nil
	}
	out := new(TenantGPUHoursQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantGPUTypeQuota) DeepCopyInto(out *TenantGPUTypeQuota) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantGPUTypeQuota.
func (in *TenantGPUTypeQuota) DeepCopy() *TenantGPUTypeQuota {
	if in == nil {
		return nil
	}
	out := new(TenantGPUTypeQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantGovernance) DeepCopyInto(out *TenantGovernance) {
	*out = *in
	if in.ComplianceRequirements != nil {
		in, out := &in.ComplianceRequirements, &out.ComplianceRequirements
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantGovernance.
func (in *TenantGovernance) DeepCopy() *TenantGovernance {
	if in == nil {
		return nil
	}
	out := new(TenantGovernance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantJobDefaults) DeepCopyInto(out *TenantJobDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantJobDefaults.
func (in *TenantJobDefaults) DeepCopy() *TenantJobDefaults {
	if in == nil {
		return nil
	}
	out := new(TenantJobDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantMember) DeepCopyInto(out *TenantMember) {
	*out = *in
	if in.JoinedAt != nil {
		in, out := &in.JoinedAt, &out.JoinedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantMember.
func (in *TenantMember) DeepCopy() *TenantMember {
	if in == nil {
		return nil
	}
	out := new(TenantMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantNetworkPolicy) DeepCopyInto(out *TenantNetworkPolicy) {
	*out = *in
	if in.AllowedTenants != nil {
		in, out := &in.AllowedTenants, &out.AllowedTenants
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantNetworkPolicy.
func (in *TenantNetworkPolicy) DeepCopy() *TenantNetworkPolicy {
	if in == nil {
		return nil
	}
	out := new(TenantNetworkPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantNotifications) DeepCopyInto(out *TenantNotifications) {
	*out = *in
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(TenantSlackConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantNotifications.
func (in *TenantNotifications) DeepCopy() *TenantNotifications {
	if in == nil {
		return nil
	}
	out := new(TenantNotifications)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantPriorities) DeepCopyInto(out *TenantPriorities) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantPriorities.
func (in *TenantPriorities) DeepCopy() *TenantPriorities {
	if in == nil {
		return nil
	}
	out := new(TenantPriorities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantQuotaUtilization) DeepCopyInto(out *TenantQuotaUtilization) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantQuotaUtilization.
func (in *TenantQuotaUtilization) DeepCopy() *TenantQuotaUtilization {
	if in == nil {
		return nil
	}
	out := new(TenantQuotaUtilization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantQuotas) DeepCopyInto(out *TenantQuotas) {
	*out = *in
	if in.GPUHours != nil {
		in, out := &in.GPUHours, &out.GPUHours
		*out = new(TenantGPUHoursQuota)
		**out = **in
	}
	if in.CostUSD != nil {
		in, out := &in.CostUSD, &out.CostUSD
		*out = new(TenantCostQuota)
		**out = **in
	}
	if in.PerGPUType != nil {
		in, out := &in.PerGPUType, &out.PerGPUType
		*out = make(map[string]TenantGPUTypeQuota, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantQuotas.
func (in *TenantQuotas) DeepCopy() *TenantQuotas {
	if in == nil {
		return nil
	}
	out := new(TenantQuotas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantSlackConfig) DeepCopyInto(out *TenantSlackConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantSlackConfig.
func (in *TenantSlackConfig) DeepCopy() *TenantSlackConfig {
	if in == nil {
		return nil
	}
	out := new(TenantSlackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantStorageQuotas) DeepCopyInto(out *TenantStorageQuotas) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantStorageQuotas.
func (in *TenantStorageQuotas) DeepCopy() *TenantStorageQuotas {
	if in == nil {
		return nil
	}
	out := new(TenantStorageQuotas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingTimeModelSpec) DeepCopyInto(out *TrainingTimeModelSpec) {
	*out = *in
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingTimeModelSpec.
func (in *TrainingTimeModelSpec) DeepCopy() *TrainingTimeModelSpec {
	if in == nil {
		return nil
	}
	out := new(TrainingTimeModelSpec)
	in.DeepCopyInto(out)
	return out
}
